package com.rpgos.app

import android.database.sqlite.SQLiteDatabase

class AssetLiabilityStore(private val db: SQLiteDatabase, private val campaignId: String) {
    init { require(campaignId.isNotBlank()); MigrationManager().ensureV14ContractGuards(db,campaignId) }

    fun registerAssetKind(d:AssetKindDefinition){AssetLiabilityPolicy.validateAssetKind(d);tx{
        OwnershipReferenceRegistry(db,campaignId).registerAssetKind(d.assetKindUid,d.provenance)
        val exists=count("SELECT COUNT(*) FROM asset_kind_definitions WHERE asset_kind_uid=?",arrayOf(d.assetKindUid))>0
        if(!exists) db.execSQL("INSERT INTO asset_kind_definitions(asset_kind_uid,asset_class,display_name,world_pack_uid,definition_status,definition_version,provenance) VALUES(?,?,?,?,?,?,?)",arrayOf<Any?>(d.assetKindUid,d.assetClass.name,d.displayName,d.worldPackUid,d.status,d.version,d.provenance))
        else require(count("SELECT COUNT(*) FROM asset_kind_definitions WHERE asset_kind_uid=? AND asset_class=? AND display_name=? AND definition_status=? AND definition_version=? AND provenance=? AND world_pack_uid IS ?",arrayOf(d.assetKindUid,d.assetClass.name,d.displayName,d.status,d.version.toString(),d.provenance,d.worldPackUid))==1L){"asset kind UID semantic conflict"}
    }}

    fun createAsset(a:AssetRecord):AssetRecord{AssetLiabilityPolicy.validateAsset(a);require(a.campaignId==campaignId);tx{
        if(assetExists(a.ref)){require(assetMatches(a)){"asset UID semantic conflict"};return@tx}
        OwnershipReferenceRegistry(db,campaignId).registerAsset(a.ref,a.provenance)
        db.execSQL("INSERT INTO asset_records(campaign_id,asset_uid,asset_kind_uid,lifecycle_status,created_order,retired_order,source_event_uid,record_version,provenance,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?)",arrayOf<Any?>(campaignId,a.assetUid,a.assetKindUid,a.lifecycle.name,a.createdOrder,a.retiredOrder,a.sourceEventUid,a.version,a.provenance,a.metadataJson))
    };return requireAsset(a.ref)}

    fun retireAsset(ref:OwnedAssetRef,at:Long,lifecycle:AssetLifecycle,provenance:String):AssetRecord{require(lifecycle!=AssetLifecycle.ACTIVE&&provenance.isNotBlank());tx{
        val cur=requireAsset(ref);require(cur.lifecycle==AssetLifecycle.ACTIVE)
        val s=db.compileStatement("UPDATE asset_records SET lifecycle_status=?,retired_order=?,record_version=record_version+1 WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=? AND lifecycle_status='ACTIVE' AND record_version=?")
        s.use{it.bindString(1,lifecycle.name);it.bindLong(2,at);it.bindString(3,campaignId);it.bindString(4,ref.assetKindUid);it.bindString(5,ref.assetUid);it.bindLong(6,cur.version);require(it.executeUpdateDelete()==1){"stale asset lifecycle"}}
        OwnershipReferenceRegistry(db,campaignId).retireAsset(ref,provenance)
    };return requireAsset(ref)}

    fun recordValuation(v:AssetValuation):AssetValuation{AssetLiabilityPolicy.validateValuation(v);require(v.campaignId==campaignId)
        if(count("SELECT COUNT(*) FROM asset_valuations WHERE campaign_id=? AND valuation_uid=?",arrayOf(campaignId,v.valuationUid))>0){require(valuationMatches(v)){"valuation UID semantic conflict"};return v}
        db.execSQL("INSERT INTO asset_valuations(campaign_id,valuation_uid,asset_kind_uid,asset_uid,currency_uid,amount_minor,valuation_type,effective_order,valid_until_order,source_event_uid,confidence_ppm,valuation_version,provenance) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",arrayOf<Any?>(campaignId,v.valuationUid,v.asset.assetKindUid,v.asset.assetUid,v.currencyUid,v.amountMinor,v.valuationType.name,v.effectiveOrder,v.validUntilOrder,v.sourceEventUid,v.confidencePpm,v.version,v.provenance));return v}

    fun createObligation(o:ObligationRecord,initialStatusEventUid:String):ObligationRecord{AssetLiabilityPolicy.validateObligation(o);require(o.campaignId==campaignId&&initialStatusEventUid.isNotBlank());tx{
        if(count("SELECT COUNT(*) FROM obligation_records WHERE campaign_id=? AND obligation_uid=?",arrayOf(campaignId,o.obligationUid))>0){require(obligationMatches(o)){"obligation UID semantic conflict"};return@tx}
        db.execSQL("INSERT INTO obligation_records(campaign_id,obligation_uid,obligation_type_uid,obligation_class,obligor_kind_uid,obligor_uid,beneficiary_kind_uid,beneficiary_uid,currency_uid,principal_minor,asset_kind_uid,asset_uid,created_order,due_order,valid_until_order,source_event_uid,source_contract_uid,record_version,provenance,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",arrayOf<Any?>(campaignId,o.obligationUid,o.obligationTypeUid,o.obligationClass.name,o.obligor.ownerKindUid,o.obligor.ownerUid,o.beneficiary.ownerKindUid,o.beneficiary.ownerUid,o.currencyUid,o.principalMinor,o.asset?.assetKindUid,o.asset?.assetUid,o.createdOrder,o.dueOrder,o.validUntilOrder,o.sourceEventUid,o.sourceContractUid,o.version,o.provenance,o.metadataJson))
        db.execSQL("INSERT INTO obligation_status_history(campaign_id,status_event_uid,obligation_uid,status,effective_order,source_event_uid,provenance) VALUES(?,?,?,'ACTIVE',?,?,?)",arrayOf<Any?>(campaignId,initialStatusEventUid,o.obligationUid,o.createdOrder,o.sourceEventUid,o.provenance))
    };return o}

    fun settle(s:ObligationSettlement):ObligationSettlement{require(s.campaignId==campaignId&&s.settlementUid.isNotBlank()&&s.obligationUid.isNotBlank()&&s.provenance.isNotBlank());require(s.amountMinor==null||s.amountMinor>0)
        if(count("SELECT COUNT(*) FROM obligation_settlements WHERE campaign_id=? AND settlement_uid=?",arrayOf(campaignId,s.settlementUid))>0){require(settlementMatches(s)){"settlement UID semantic conflict"};return s}
        db.execSQL("INSERT INTO obligation_settlements(campaign_id,settlement_uid,obligation_uid,settlement_kind,amount_minor,financial_transaction_uid,ownership_operation_uid,effective_order,source_event_uid,provenance) VALUES(?,?,?,?,?,?,?,?,?,?)",arrayOf<Any?>(campaignId,s.settlementUid,s.obligationUid,s.kind.name,s.amountMinor,s.financialTransactionUid,s.ownershipOperationUid,s.effectiveOrder,s.sourceEventUid,s.provenance));return s}

    fun changeObligationStatus(obligationUid:String,eventUid:String,status:ObligationStatus,at:Long,provenance:String,sourceEventUid:String?=null){require(obligationUid.isNotBlank()&&eventUid.isNotBlank()&&provenance.isNotBlank());db.execSQL("INSERT INTO obligation_status_history(campaign_id,status_event_uid,obligation_uid,status,effective_order,source_event_uid,provenance) VALUES(?,?,?,?,?,?,?)",arrayOf<Any?>(campaignId,eventUid,obligationUid,status.name,at,sourceEventUid,provenance))}

    fun outstandingMinor(uid:String,at:Long=Long.MAX_VALUE):Long?{val principal=db.rawQuery("SELECT principal_minor FROM obligation_records WHERE campaign_id=? AND obligation_uid=?",arrayOf(campaignId,uid)).use{c->if(!c.moveToFirst())error("obligation not found") else if(c.isNull(0))return null else c.getLong(0)};var paid=0L;db.rawQuery("SELECT amount_minor FROM obligation_settlements WHERE campaign_id=? AND obligation_uid=? AND amount_minor IS NOT NULL AND effective_order<=? ORDER BY effective_order,settlement_uid",arrayOf(campaignId,uid,at.toString())).use{c->while(c.moveToNext())paid=Math.addExact(paid,c.getLong(0))};return Math.subtractExact(principal,paid)}
    fun currentStatus(uid:String,at:Long=Long.MAX_VALUE):ObligationStatus?=db.rawQuery("SELECT status FROM obligation_status_history WHERE campaign_id=? AND obligation_uid=? AND effective_order<=? ORDER BY effective_order DESC,status_event_uid DESC LIMIT 1",arrayOf(campaignId,uid,at.toString())).use{c->if(c.moveToFirst())ObligationStatus.valueOf(c.getString(0)) else null}

    fun addEncumbrance(uid:String,asset:OwnedAssetRef,obligationUid:String,typeUid:String,priority:Int,at:Long,provenance:String){require(uid.isNotBlank()&&typeUid.isNotBlank()&&provenance.isNotBlank());db.execSQL("INSERT INTO asset_encumbrances(campaign_id,encumbrance_uid,asset_kind_uid,asset_uid,obligation_uid,encumbrance_type_uid,priority,valid_from_order,record_version,provenance) VALUES(?,?,?,?,?,?,?,?,1,?)",arrayOf(campaignId,uid,asset.assetKindUid,asset.assetUid,obligationUid,typeUid,priority,at,provenance))}
    fun releaseEncumbrance(uid:String,at:Long,provenance:String){require(uid.isNotBlank()&&provenance.isNotBlank());val s=db.compileStatement("UPDATE asset_encumbrances SET released_order=?,record_version=record_version+1,release_provenance=? WHERE campaign_id=? AND encumbrance_uid=? AND released_order IS NULL");s.use{it.bindLong(1,at);it.bindString(2,provenance);it.bindString(3,campaignId);it.bindString(4,uid);require(it.executeUpdateDelete()==1){"active encumbrance not found"}}}

    /** Pure derived projection: Assets + historical cash + receivables - liabilities. */
    fun netWorth(p:OwnershipOwnerRef,currency:String,at:Long):NetWorthProjection{OwnershipPolicy.validateOwner(p);require(currency.isNotBlank());var assets=0L
        db.rawQuery("SELECT r.asset_kind_uid,r.asset_uid,r.share_units FROM ownership_records r JOIN asset_records a ON a.campaign_id=r.campaign_id AND a.asset_kind_uid=r.asset_kind_uid AND a.asset_uid=r.asset_uid WHERE r.campaign_id=? AND r.owner_kind_uid=? AND r.owner_uid=? AND r.ownership_type_uid=? AND r.valid_from_order<=? AND (r.valid_until_order IS NULL OR ?<r.valid_until_order) AND a.created_order<=? AND (a.retired_order IS NULL OR ?<a.retired_order)",arrayOf(campaignId,p.ownerKindUid,p.ownerUid,OWNERSHIP_TYPE_ECONOMIC,at.toString(),at.toString(),at.toString(),at.toString())).use{c->while(c.moveToNext()){val value=valuationAt(OwnedAssetRef(c.getString(0),c.getString(1)),currency,at);if(value!=null)assets=Math.addExact(assets,AssetLiabilityPolicy.exactShareValue(value,c.getLong(2)))}}
        val cash=cashAt(p,currency,at);var receivables=0L;var liabilities=0L
        db.rawQuery("SELECT obligation_uid,obligor_kind_uid,obligor_uid,beneficiary_kind_uid,beneficiary_uid FROM obligation_records WHERE campaign_id=? AND currency_uid=? AND created_order<=? AND (valid_until_order IS NULL OR ?<valid_until_order)",arrayOf(campaignId,currency,at.toString(),at.toString())).use{c->while(c.moveToNext()){val uid=c.getString(0);val st=currentStatus(uid,at);if(st!=null&&st !in setOf(ObligationStatus.SETTLED,ObligationStatus.CANCELLED,ObligationStatus.EXPIRED)){val out=outstandingMinor(uid,at)?:0L;if(c.getString(1)==p.ownerKindUid&&c.getString(2)==p.ownerUid)liabilities=Math.addExact(liabilities,out);if(c.getString(3)==p.ownerKindUid&&c.getString(4)==p.ownerUid)receivables=Math.addExact(receivables,out)}}}
        val net=Math.subtractExact(Math.addExact(Math.addExact(assets,cash),receivables),liabilities);return NetWorthProjection(campaignId,p,currency,at,assets,cash,receivables,liabilities,net)}

    fun assetCount()=count("SELECT COUNT(*) FROM asset_records WHERE campaign_id=?",arrayOf(campaignId))
    fun obligationCount()=count("SELECT COUNT(*) FROM obligation_records WHERE campaign_id=?",arrayOf(campaignId))

    private fun valuationAt(a:OwnedAssetRef,currency:String,at:Long):Long?=db.rawQuery("SELECT amount_minor FROM asset_valuations WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=? AND currency_uid=? AND effective_order<=? AND (valid_until_order IS NULL OR ?<valid_until_order) ORDER BY effective_order DESC,valuation_uid DESC LIMIT 1",arrayOf(campaignId,a.assetKindUid,a.assetUid,currency,at.toString(),at.toString())).use{c->if(c.moveToFirst())c.getLong(0) else null}
    private fun cashAt(p:OwnershipOwnerRef,currency:String,at:Long):Long{var total=0L;db.rawQuery("SELECT account_uid FROM financial_accounts WHERE campaign_id=? AND holder_kind_uid=? AND holder_uid=? AND currency_uid=? AND opened_order<=? AND (closed_order IS NULL OR ?<closed_order)",arrayOf(campaignId,p.ownerKindUid,p.ownerUid,currency,at.toString(),at.toString())).use{a->while(a.moveToNext()){val account=a.getString(0);var bal=0L;db.rawQuery("SELECT from_account_uid,to_account_uid,amount_minor FROM financial_ledger_transactions WHERE campaign_id=? AND (from_account_uid=? OR to_account_uid=?) AND effective_order<=? ORDER BY effective_order,financial_transaction_uid",arrayOf(campaignId,account,account,at.toString())).use{t->while(t.moveToNext()){if(!t.isNull(0)&&t.getString(0)==account)bal=Math.subtractExact(bal,t.getLong(2));if(!t.isNull(1)&&t.getString(1)==account)bal=Math.addExact(bal,t.getLong(2))}};total=Math.addExact(total,bal)}};return total}
    private fun assetExists(a:OwnedAssetRef)=count("SELECT COUNT(*) FROM asset_records WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=?",arrayOf(campaignId,a.assetKindUid,a.assetUid))>0
    private fun assetMatches(a:AssetRecord)=count("SELECT COUNT(*) FROM asset_records WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=? AND lifecycle_status=? AND created_order=? AND record_version=? AND provenance=? AND source_event_uid IS ? AND metadata_json IS ? AND retired_order IS ?",arrayOf(campaignId,a.assetKindUid,a.assetUid,a.lifecycle.name,a.createdOrder.toString(),a.version.toString(),a.provenance,a.sourceEventUid,a.metadataJson,a.retiredOrder?.toString()))==1L
    private fun valuationMatches(v:AssetValuation)=count("SELECT COUNT(*) FROM asset_valuations WHERE campaign_id=? AND valuation_uid=? AND asset_kind_uid=? AND asset_uid=? AND currency_uid=? AND amount_minor=? AND valuation_type=? AND effective_order=? AND valuation_version=? AND provenance=?",arrayOf(campaignId,v.valuationUid,v.asset.assetKindUid,v.asset.assetUid,v.currencyUid,v.amountMinor.toString(),v.valuationType.name,v.effectiveOrder.toString(),v.version.toString(),v.provenance))==1L
    private fun obligationMatches(o:ObligationRecord)=count("SELECT COUNT(*) FROM obligation_records WHERE campaign_id=? AND obligation_uid=? AND obligation_type_uid=? AND obligation_class=? AND obligor_kind_uid=? AND obligor_uid=? AND beneficiary_kind_uid=? AND beneficiary_uid=? AND created_order=? AND provenance=?",arrayOf(campaignId,o.obligationUid,o.obligationTypeUid,o.obligationClass.name,o.obligor.ownerKindUid,o.obligor.ownerUid,o.beneficiary.ownerKindUid,o.beneficiary.ownerUid,o.createdOrder.toString(),o.provenance))==1L
    private fun settlementMatches(s:ObligationSettlement)=count("SELECT COUNT(*) FROM obligation_settlements WHERE campaign_id=? AND settlement_uid=? AND obligation_uid=? AND settlement_kind=? AND effective_order=? AND provenance=?",arrayOf(campaignId,s.settlementUid,s.obligationUid,s.kind.name,s.effectiveOrder.toString(),s.provenance))==1L
    private fun requireAsset(a:OwnedAssetRef):AssetRecord=db.rawQuery("SELECT lifecycle_status,created_order,retired_order,source_event_uid,record_version,provenance,metadata_json FROM asset_records WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=?",arrayOf(campaignId,a.assetKindUid,a.assetUid)).use{c->require(c.moveToFirst()){"Phase14 asset not found"};AssetRecord(campaignId,a.assetUid,a.assetKindUid,c.getLong(1),c.getString(5),AssetLifecycle.valueOf(c.getString(0)),if(c.isNull(2))null else c.getLong(2),if(c.isNull(3))null else c.getString(3),c.getLong(4),if(c.isNull(6))null else c.getString(6))}
    private fun count(sql:String,args:Array<String>)=db.rawQuery(sql,args).use{c->c.moveToFirst();c.getLong(0)}
    private fun tx(block:()->Unit){if(db.inTransaction()){block();return};db.beginTransaction();try{block();db.setTransactionSuccessful()}finally{db.endTransaction()}}
}
