package com.rpgos.app

import android.database.sqlite.SQLiteDatabase

class ContextBuilder(private val saveDb: SQLiteDatabase, private val worldDb: SQLiteDatabase) {
    fun build(playerInput: String, chapter: Int): ContextBundle {
        val campaignRef = ActiveCampaignRef.fromDatabasePath(saveDb.path)
        val campaign = safeQueryOne(saveDb,"SELECT campaign_name,schema_version,current_chapter,current_tome FROM campaign_meta WHERE id=1")
        val time = safeQueryOne(saveDb,"SELECT year_label,era_name,season,hour,minute,absolute_day FROM campaign_calendar WHERE id=1")
        val playerUid = ActivePlayerStore(saveDb,campaignRef.campaignId).active()?.playerUid
        val position = if(playerUid!=null) safeQueryOne(saveDb,"SELECT entity_uid,location_uid,x_coord,y_coord,last_updated_day,updated_chapter FROM entity_positions WHERE entity_uid=? LIMIT 1",arrayOf(playerUid)) else emptyMap()
        val typedStats=if(playerUid!=null)safeQueryMany(saveDb,"SELECT stat_uid,base_value,version FROM player_stats WHERE campaign_id=? AND character_uid=? ORDER BY stat_uid",arrayOf(campaignRef.campaignId,playerUid))else emptyList()
        val typedResources=if(playerUid!=null)safeQueryMany(saveDb,"SELECT resource_uid,current_value,version FROM player_resources WHERE campaign_id=? AND character_uid=? ORDER BY resource_uid",arrayOf(campaignRef.campaignId,playerUid))else emptyList()
        val ownership=if(playerUid!=null)safeQueryMany(saveDb,"SELECT ownership_record_uid,owner_kind_uid,owner_uid,asset_kind_uid,asset_uid,ownership_type_uid,share_units,valid_from_order,record_version,provenance FROM ownership_records WHERE campaign_id=? AND owner_kind_uid='CHARACTER' AND owner_uid=? AND record_status='ACTIVE' AND valid_until_order IS NULL ORDER BY asset_kind_uid,asset_uid,ownership_type_uid",arrayOf(campaignRef.campaignId,playerUid))else emptyList()
        val projects=if(playerUid!=null)safeQueryMany(saveDb,"SELECT project_uid,project_type_uid,title,objective_summary,target_domain_uid,target_kind_uid,target_uid,intended_output_kind_uid,progress_cap_units,created_order,started_order,project_version,source_event_uid,provenance FROM development_projects WHERE campaign_id=? AND ((initiator_kind_uid='CHARACTER' AND initiator_uid=?) OR (beneficiary_kind_uid='CHARACTER' AND beneficiary_uid=?)) ORDER BY project_uid",arrayOf(campaignRef.campaignId,playerUid,playerUid))else emptyList()
        val status=linkedMapOf<String,Any?>("chapter" to chapter,"player_input" to playerInput,"player_uid" to playerUid,"campaign" to campaign).apply{
            position.forEach{(k,v)->put(k,v)}
            if(playerUid!=null){put("finance_ledger",FinancialContextReader(saveDb,campaignRef.campaignId).forPlayerUid(playerUid));put("injuries",safeQueryMany(saveDb,"SELECT injury_uid,body_part_uid,severity,pain,bleeding,status,created_chapter FROM injuries_v2 WHERE entity_uid=? AND status!='healed' ORDER BY severity DESC LIMIT 12",arrayOf(playerUid)));put("typed_stats",typedStats);put("typed_resources",typedResources);put("ownership",ownership);put("projects",projects)}
        }
        val scene=linkedMapOf<String,Any?>("query" to playerInput,"player_uid" to playerUid).apply{position.forEach{(k,v)->put(k,v)};val locationUid=position["location_uid"] as? String;if(!locationUid.isNullOrBlank())safeQueryOne(worldDb,"SELECT location_uid,name,location_type,region_uid,description FROM map_locations_v2 WHERE location_uid=? LIMIT 1",arrayOf(locationUid)).forEach{(k,v)->put("location_$k",v)}}
        val threads=safeQueryMany(saveDb,"SELECT thread_uid,title,thread_type,status,priority,last_advanced_chapter,description FROM story_threads WHERE status='active' ORDER BY priority DESC,last_advanced_chapter DESC LIMIT 20")
        val missions=safeQueryMany(saveDb,"SELECT mission_uid,title,mission_rank,status,objective_summary,reward_ryo,deadline_day,location_uid,consequence_on_failure FROM missions_v3 WHERE status IN ('available','active','assigned') ORDER BY CASE status WHEN 'active' THEN 0 WHEN 'assigned' THEN 1 ELSE 2 END,reward_ryo DESC LIMIT 20")
        val pressures=safeQueryMany(saveDb,"SELECT pressure_uid,target_type,target_uid,starts_day,peaks_day,pressure_type,magnitude,hidden,summary FROM future_world_pressure ORDER BY magnitude DESC LIMIT 20")
        val activeWorldEvents=safeQueryMany(saveDb,"SELECT active_event_uid,event_type,subject_uid,location_uid,started_day,expected_end_day,status,visibility,public_summary,gm_summary FROM active_world_events WHERE status='active' ORDER BY started_day DESC LIMIT 20")
        val chronicle=safeQueryMany(saveDb,"SELECT chapter,title,active_threads_json,decisions_json,consequences_json,quests_json,continuity_warnings_json FROM chapter_manifests_v2 ORDER BY chapter DESC LIMIT 10")
        val longTermMemory=safeQueryMany(saveDb,"SELECT memory_uid,entity_uid,memory_type,subject_uid,chapter,day,importance,emotional_valence,accuracy,summary FROM npc_memories_v2 WHERE active=1 ORDER BY importance DESC,chapter DESC LIMIT 30")
        val relevantNpcIds=LinkedHashSet<String>();safeQueryMany(saveDb,"SELECT entity_uid,location_uid,priority,summary FROM npc_schedules WHERE visibility IN ('gm','public') ORDER BY priority DESC LIMIT 20").forEach{(it["entity_uid"] as? String)?.let(relevantNpcIds::add)};safeQueryMany(saveDb,"SELECT holder_uid FROM information_knowledge ORDER BY confidence DESC,learned_chapter DESC LIMIT 20").forEach{(it["holder_uid"] as? String)?.let(relevantNpcIds::add)}
        val npcRows=mutableListOf<Map<String,Any?>>();val knowledgeRows=mutableListOf<Map<String,Any?>>();val npcMemoryRows=mutableListOf<Map<String,Any?>>()
        for(id in relevantNpcIds.take(16)){val npc=safeQueryOne(worldDb,"SELECT character_uid,name,sex,birth_era,clan_uid,village_uid,rank_title,affiliation_summary,personality_summary,combat_summary FROM canon_characters_v2 WHERE character_uid=? LIMIT 1",arrayOf(id));if(npc.isNotEmpty())npcRows+=npc;knowledgeRows+=safeQueryMany(saveDb,"SELECT k.holder_uid,k.info_uid,k.confidence,k.accuracy,k.acquisition_method,k.learned_chapter,f.title,f.content_summary,f.secrecy_level FROM information_knowledge k LEFT JOIN information_facts f ON f.info_uid=k.info_uid WHERE k.holder_uid=? ORDER BY k.confidence DESC,k.learned_chapter DESC LIMIT 16",arrayOf(id));npcMemoryRows+=safeQueryMany(saveDb,"SELECT memory_uid,entity_uid,memory_type,subject_uid,chapter,day,importance,emotional_valence,accuracy,summary FROM npc_memories_v2 WHERE entity_uid=? AND active=1 ORDER BY importance DESC,chapter DESC LIMIT 12",arrayOf(id))}
        val constraints=safeQueryMany(worldDb,"SELECT constraint_uid,subject_type,subject_uid,constraint_key,constraint_value,canon_scope,notes FROM canon_constraints_v2 WHERE status='active' OR status IS NULL LIMIT 40")
        val skills=if(playerUid!=null){val r=SkillStore(saveDb,campaignRef.campaignId).reconciled(playerUid);r.skills.map{i->val s=i.playerSkill;linkedMapOf<String,Any?>("entity_uid" to s.characterUid,"skill_uid" to s.skillUid,"mastery" to s.baseMastery,"base_mastery" to s.baseMastery,"progress_value" to s.progressValue,"progress_semantics_uid" to s.progressSemanticsUid,"entry_version" to s.entryVersion,"provenance" to s.provenance,"learned_chapter" to s.learnedChapter,"authority_source" to i.authoritySource.name,"legacy_xp_raw" to i.legacyXpRaw,"legacy_updated_chapter_raw" to i.legacyUpdatedChapterRaw,"canonical" to true)}+r.unresolvedLegacy.map{l->linkedMapOf<String,Any?>("entity_uid" to l.characterUid,"skill_uid" to l.legacySkillUid,"mastery_raw" to l.masteryRaw,"xp_raw" to l.xpRaw,"updated_chapter_raw" to l.updatedChapterRaw,"display_name" to l.displayName,"category" to l.category,"authority_source" to "LEGACY_UNRESOLVED","canonical" to false)}}else emptyList()
        val techniques=if(playerUid!=null){val r=TechniqueStore(saveDb,campaignRef.campaignId).reconciled(playerUid);r.techniques.map{i->val t=i.playerTechnique;linkedMapOf<String,Any?>("entity_uid" to t.characterUid,"technique_uid" to t.techniqueUid,"mastery" to t.baseMastery,"base_mastery" to t.baseMastery,"progress_value" to t.progressValue,"progress_semantics_uid" to t.progressSemanticsUid,"learned_chapter" to t.learnedChapter,"last_used_chapter" to t.lastUsedChapter,"usage_count" to t.usageCount,"success_count" to t.successCount,"failure_count" to t.failureCount,"is_equipped" to t.isEquipped,"notes" to t.notes,"entry_version" to t.entryVersion,"provenance" to t.provenance,"authority_source" to i.authoritySource.name,"legacy_xp_raw" to i.legacyXpRaw,"legacy_chakra_cost_override_raw" to i.legacyChakraCostOverrideRaw,"legacy_base_chakra_cost_raw" to i.legacyBaseChakraCostRaw,"mapped_legacy_cost_resource_uid" to i.mappedLegacyCostResourceUid,"canonical" to true)}+r.unresolvedLegacy.map{l->linkedMapOf<String,Any?>("entity_uid" to l.characterUid,"technique_uid" to l.legacyTechniqueUid,"mastery_raw" to l.masteryRaw,"xp_raw" to l.xpRaw,"learned_chapter_raw" to l.learnedChapterRaw,"last_used_chapter_raw" to l.lastUsedChapterRaw,"usage_count_raw" to l.usageCountRaw,"success_count_raw" to l.successCountRaw,"failure_count_raw" to l.failureCountRaw,"is_equipped_raw" to l.isEquippedRaw,"notes_raw" to l.notesRaw,"display_name" to l.displayName,"category" to l.category,"legacy_chakra_cost_override_raw" to l.chakraCostOverrideRaw,"legacy_base_chakra_cost_raw" to l.baseChakraCostRaw,"authority_source" to "LEGACY_UNRESOLVED","canonical" to false)}}else emptyList()
        val inventory=if(playerUid!=null){val r=InventoryStore(saveDb,campaignRef.campaignId).reconciled(playerUid);val stacks=r.stacks.map{i->linkedMapOf<String,Any?>("entity_uid" to i.stack.characterUid,"item_definition_uid" to i.stack.itemDefinitionUid,"quantity" to i.stack.quantity,"entry_version" to i.stack.entryVersion,"provenance" to i.stack.provenance,"authority_source" to i.authoritySource.name,"mapped_legacy_evidence_uid" to i.mappedLegacyEvidenceUid,"canonical" to true,"equipped" to null,"ownership_record" to null)};val unique=r.uniqueItems.map{i->linkedMapOf<String,Any?>("entity_uid" to i.entry.characterUid,"item_definition_uid" to i.instance.itemDefinitionUid,"item_instance_uid" to i.entry.itemInstanceUid,"entry_version" to i.entry.entryVersion,"provenance" to i.entry.provenance,"authority_source" to i.authoritySource.name,"mapped_legacy_evidence_uid" to i.mappedLegacyEvidenceUid,"canonical" to true,"equipped" to null,"ownership_record" to null)};val unresolved=r.unresolvedLegacy.map{e->linkedMapOf<String,Any?>("entity_uid" to e.characterUid,"legacy_evidence_uid" to e.evidenceUid,"item_name" to e.itemName,"row_count" to e.rowCount,"raw_fields" to e.rawFields,"authority_source" to "LEGACY_UNRESOLVED","canonical" to false,"equipped" to null,"ownership_record" to null)};stacks+unique+unresolved}else emptyList()
        val organizations=if(playerUid!=null)safeQueryMany(saveDb,"SELECT organization_uid,character_uid,unit_uid,position_uid,role_title,loyalty,secrecy_clearance,joined_era,status FROM organization_memberships_v3 WHERE character_uid=? AND status='active' ORDER BY loyalty DESC",arrayOf(playerUid))else emptyList()
        val campaignTruth=CampaignTruthStore(saveDb,campaignRef.campaignId).activeForContext()
        val playerState=PlayerStateStore(saveDb,campaignRef.campaignId).load()?.toContextMap()?:emptyMap()
        val meta=linkedMapOf<String,Any?>("engine" to "ContextBundle Engine v1","schema" to 1,"campaign_id" to campaignRef.campaignId,"campaign_directory" to campaignRef.directoryName,"chapter" to chapter,"player_uid" to playerUid,"player_uid_source" to "active_player_ref","player_uid_resolved" to (playerUid!=null),"threads" to threads.size,"missions" to missions.size,"pressures" to pressures.size,"world_events" to activeWorldEvents.size,"npcs" to npcRows.size,"npc_knowledge" to knowledgeRows.size,"npc_memories" to npcMemoryRows.size,"long_term_memory" to longTermMemory.size,"skills" to skills.size,"techniques" to techniques.size,"inventory" to inventory.size,"organizations" to organizations.size,"campaign_truth" to campaignTruth.size,"typed_stats" to typedStats.size,"typed_resources" to typedResources.size,"ownership" to ownership.size,"projects" to projects.size,"player_state_resolved" to (playerState.isNotEmpty()))
        return ContextBundle(status,scene,time,threads,npcRows,knowledgeRows,missions,pressures,constraints,chronicle,longTermMemory,skills,techniques,inventory,organizations,activeWorldEvents,npcMemoryRows,campaignTruth=campaignTruth,playerState=playerState,contextMeta=meta)
    }
    private fun safeQueryOne(db:SQLiteDatabase,sql:String,args:Array<String>?=null):Map<String,Any?> = safeQueryMany(db,sql,args).firstOrNull()?:emptyMap()
    private fun safeQueryMany(db:SQLiteDatabase,sql:String,args:Array<String>?=null):List<Map<String,Any?>> = try{queryMany(db,sql,args)}catch(_:Throwable){emptyList()}
    private fun queryMany(db:SQLiteDatabase,sql:String,args:Array<String>?=null):List<Map<String,Any?>>{val out=mutableListOf<Map<String,Any?>>();db.rawQuery(sql,args).use{c->val names=c.columnNames;while(c.moveToNext()){val row=LinkedHashMap<String,Any?>();for(i in names.indices)row[names[i]]=when(c.getType(i)){android.database.Cursor.FIELD_TYPE_NULL->null;android.database.Cursor.FIELD_TYPE_INTEGER->c.getLong(i);android.database.Cursor.FIELD_TYPE_FLOAT->c.getDouble(i);android.database.Cursor.FIELD_TYPE_BLOB->"[BLOB ${c.getBlob(i).size} bytes]";else->c.getString(i)};out+=row}};return out}
}
