package com.rpgos.app

import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import java.nio.charset.StandardCharsets
import java.security.MessageDigest

class InventoryStore(private val db:SQLiteDatabase,private val campaignId:String){
 init{require(campaignId.isNotBlank());MigrationManager().ensureV10(db,campaignId)}
 fun registerDefinitions(worldPackUid:String,definitions:List<ItemDefinition>){require(worldPackUid.isNotBlank());db.beginTransaction();try{definitions.forEach{d->InventoryPolicy.requireDefinition(d);require(d.worldPackUid==worldPackUid);require(!exists("item_definitions_v2","item_definition_uid",d.itemDefinitionUid)){"Duplicate item definition UID: ${d.itemDefinitionUid}"};require(!db.rawQuery("SELECT 1 FROM item_definitions_v2 WHERE world_pack_uid=? AND item_key=? LIMIT 1",arrayOf(worldPackUid,d.key)).use{it.moveToFirst()}){"Duplicate item key for World Pack: ${d.key}"};db.execSQL("INSERT INTO item_definitions_v2(item_definition_uid,world_pack_uid,item_key,display_name,category,storage_policy,definition_status,definition_version,provenance) VALUES(?,?,?,?,?,?,?,?,?)",arrayOf(d.itemDefinitionUid,d.worldPackUid,d.key,d.displayName,d.category,d.storagePolicy.name,d.definitionStatus.name,d.definitionVersion,d.provenance))};db.setTransactionSuccessful()}finally{db.endTransaction()}}
 fun definitions(worldPackUid:String?=null):List<ItemDefinition>{val w=if(worldPackUid==null)"" else " WHERE world_pack_uid=?";val a=worldPackUid?.let{arrayOf(it)};val out=mutableListOf<ItemDefinition>();db.rawQuery("SELECT item_definition_uid,world_pack_uid,item_key,display_name,category,storage_policy,definition_status,definition_version,provenance FROM item_definitions_v2$w ORDER BY world_pack_uid,item_key,item_definition_uid",a).use{c->while(c.moveToNext())out+=ItemDefinition(c.getString(0),c.getString(1),c.getString(2),c.getString(3),if(c.isNull(4))null else c.getString(4),ItemStoragePolicy.valueOf(c.getString(5)),ItemDefinitionStatus.valueOf(c.getString(6)),c.getLong(7),c.getString(8))};return out}
 fun createInstance(i:ItemInstance){require(i.campaignId==campaignId);require(i.itemInstanceUid.isNotBlank()&&i.provenance.isNotBlank()&&i.instanceVersion>=1);require(definition(i.itemDefinitionUid).storagePolicy==ItemStoragePolicy.UNIQUE_INSTANCE);require(!instanceExists(i.itemInstanceUid));db.execSQL("INSERT INTO item_instances(campaign_id,item_instance_uid,item_definition_uid,instance_version,provenance) VALUES(?,?,?,?,?)",arrayOf(campaignId,i.itemInstanceUid,i.itemDefinitionUid,i.instanceVersion,i.provenance))}
 fun addStack(characterUid:String,itemDefinitionUid:String,quantity:Long,provenance:String,entryVersion:Long=1){requireCharacter(characterUid,provenance,entryVersion);InventoryPolicy.requireQuantity(quantity);require(definition(itemDefinitionUid).storagePolicy==ItemStoragePolicy.STACKABLE);db.beginTransaction();try{val current=stackQuantity(characterUid,itemDefinitionUid);if(current==null)db.execSQL("INSERT INTO player_inventory_stacks(campaign_id,character_uid,item_definition_uid,quantity,entry_version,provenance) VALUES(?,?,?,?,?,?)",arrayOf(campaignId,characterUid,itemDefinitionUid,quantity,entryVersion,provenance)) else db.execSQL("UPDATE player_inventory_stacks SET quantity=?,entry_version=entry_version+1,provenance=? WHERE campaign_id=? AND character_uid=? AND item_definition_uid=?",arrayOf(InventoryPolicy.checkedAdd(current,quantity),provenance,campaignId,characterUid,itemDefinitionUid));db.setTransactionSuccessful()}finally{db.endTransaction()}}
 fun removeStack(characterUid:String,itemDefinitionUid:String,quantity:Long,provenance:String){require(characterUid.isNotBlank()&&provenance.isNotBlank());InventoryPolicy.requireQuantity(quantity);db.beginTransaction();try{val current=stackQuantity(characterUid,itemDefinitionUid)?:error("Inventory stack is missing");require(quantity<=current);if(quantity==current)db.delete("player_inventory_stacks","campaign_id=? AND character_uid=? AND item_definition_uid=?",arrayOf(campaignId,characterUid,itemDefinitionUid)) else db.execSQL("UPDATE player_inventory_stacks SET quantity=?,entry_version=entry_version+1,provenance=? WHERE campaign_id=? AND character_uid=? AND item_definition_uid=?",arrayOf(current-quantity,provenance,campaignId,characterUid,itemDefinitionUid));db.setTransactionSuccessful()}finally{db.endTransaction()}}
 fun addUnique(characterUid:String,itemInstanceUid:String,provenance:String,entryVersion:Long=1){requireCharacter(characterUid,provenance,entryVersion);val i=instance(itemInstanceUid);require(definition(i.itemDefinitionUid).storagePolicy==ItemStoragePolicy.UNIQUE_INSTANCE);require(db.rawQuery("SELECT 1 FROM player_inventory_unique WHERE campaign_id=? AND item_instance_uid=? LIMIT 1",arrayOf(campaignId,itemInstanceUid)).use{!it.moveToFirst()});db.execSQL("INSERT INTO player_inventory_unique(campaign_id,character_uid,item_instance_uid,entry_version,provenance) VALUES(?,?,?,?,?)",arrayOf(campaignId,characterUid,itemInstanceUid,entryVersion,provenance))}
 fun removeUnique(characterUid:String,itemInstanceUid:String){require(db.delete("player_inventory_unique","campaign_id=? AND character_uid=? AND item_instance_uid=?",arrayOf(campaignId,characterUid,itemInstanceUid))==1)}
 fun typedStacks(characterUid:String):List<PlayerInventoryStack>{val out=mutableListOf<PlayerInventoryStack>();db.rawQuery("SELECT campaign_id,character_uid,item_definition_uid,quantity,entry_version,provenance FROM player_inventory_stacks WHERE campaign_id=? AND character_uid=? ORDER BY item_definition_uid",arrayOf(campaignId,characterUid)).use{c->while(c.moveToNext())out+=PlayerInventoryStack(c.getString(0),c.getString(1),c.getString(2),c.getLong(3),c.getLong(4),c.getString(5))};return out}
 fun typedUnique(characterUid:String):List<Pair<PlayerInventoryUnique,ItemInstance>>{val out=mutableListOf<Pair<PlayerInventoryUnique,ItemInstance>>();db.rawQuery("SELECT u.campaign_id,u.character_uid,u.item_instance_uid,u.entry_version,u.provenance,i.item_definition_uid,i.instance_version,i.provenance FROM player_inventory_unique u JOIN item_instances i ON i.campaign_id=u.campaign_id AND i.item_instance_uid=u.item_instance_uid WHERE u.campaign_id=? AND u.character_uid=? ORDER BY u.item_instance_uid",arrayOf(campaignId,characterUid)).use{c->while(c.moveToNext()){val e=PlayerInventoryUnique(c.getString(0),c.getString(1),c.getString(2),c.getLong(3),c.getString(4));out+=e to ItemInstance(campaignId,c.getString(2),c.getString(5),c.getLong(6),c.getString(7))}};return out}
 fun legacyEvidence(characterUid:String):List<LegacyInventoryEvidence>{if(!tableExists("character_inventory")||tableColumns("character_inventory").none{it.equals("entity_uid",true)})return emptyList();val groups=linkedMapOf<String,Group>();db.rawQuery("SELECT * FROM character_inventory WHERE entity_uid=?",arrayOf(characterUid)).use{c->while(c.moveToNext()){val raw=linkedMapOf<String,String?>();c.columnNames.forEachIndexed{i,n->if(!n.equals("entity_uid",true))raw[n]=cursorString(c,i)};val sig=raw.entries.sortedBy{it.key.lowercase()}.joinToString("\u001f"){"${it.key.lowercase()}=${it.value?:"<NULL>"}"};val uid=legacyUid(sig);val g=groups.getOrPut(uid){Group(raw,0)};g.count=Math.addExact(g.count,1)}};return groups.map{(uid,g)->LegacyInventoryEvidence(campaignId,characterUid,uid,g.raw.entries.firstOrNull{it.key.equals("item_name",true)}?.value,g.count,g.raw)}.sortedBy{it.evidenceUid}}
 fun registerLegacyMappings(worldPackUid:String,mappings:List<LegacyInventoryMapping>){db.beginTransaction();try{mappings.forEach{m->require(m.campaignId==campaignId&&m.characterUid.isNotBlank()&&m.legacyEvidenceUid.isNotBlank()&&m.worldPackUid==worldPackUid&&m.mappingVersion>=1&&m.provenance.isNotBlank());val d=definition(m.canonicalItemDefinitionUid);require(d.worldPackUid==worldPackUid);when(d.storagePolicy){ItemStoragePolicy.STACKABLE->require(m.canonicalItemInstanceUid==null);ItemStoragePolicy.UNIQUE_INSTANCE->{val u=m.canonicalItemInstanceUid?:error("Unique legacy mapping requires explicit itemInstanceUid");require(instance(u).itemDefinitionUid==d.itemDefinitionUid)}};val e=legacyEvidence(m.characterUid).singleOrNull{it.evidenceUid==m.legacyEvidenceUid}?:error("Legacy inventory evidence is missing or changed");if(d.storagePolicy==ItemStoragePolicy.UNIQUE_INSTANCE)require(e.rowCount==1L);val old=db.rawQuery("SELECT canonical_item_definition_uid,canonical_item_instance_uid,world_pack_uid,mapping_version,provenance FROM legacy_inventory_mappings WHERE campaign_id=? AND character_uid=? AND legacy_evidence_uid=?",arrayOf(campaignId,m.characterUid,m.legacyEvidenceUid)).use{c->if(!c.moveToFirst())false else{require(c.getString(0)==m.canonicalItemDefinitionUid&&(if(c.isNull(1))null else c.getString(1))==m.canonicalItemInstanceUid&&c.getString(2)==m.worldPackUid&&c.getLong(3)==m.mappingVersion&&c.getString(4)==m.provenance);true}};if(!old)db.execSQL("INSERT INTO legacy_inventory_mappings(campaign_id,character_uid,legacy_evidence_uid,canonical_item_definition_uid,canonical_item_instance_uid,world_pack_uid,mapping_version,provenance) VALUES(?,?,?,?,?,?,?,?)",arrayOf(campaignId,m.characterUid,m.legacyEvidenceUid,m.canonicalItemDefinitionUid,m.canonicalItemInstanceUid,m.worldPackUid,m.mappingVersion,m.provenance))};db.setTransactionSuccessful()}finally{db.endTransaction()}}
 fun reconciled(characterUid:String):ReconciledInventory{val ts=typedStacks(characterUid).associateBy{it.itemDefinitionUid};val tu=typedUnique(characterUid).associateBy{it.first.itemInstanceUid};val sv=ts.values.map{InventoryStackView(it,InventoryAuthoritySource.TYPED)}.toMutableList();val uv=tu.values.map{InventoryUniqueView(it.first,it.second,InventoryAuthoritySource.TYPED)}.toMutableList();val unresolved=mutableListOf<LegacyInventoryEvidence>();val maps=mappings(characterUid).associateBy{it.legacyEvidenceUid};legacyEvidence(characterUid).forEach{e->val m=maps[e.evidenceUid];if(m==null){unresolved+=e;return@forEach};val d=definition(m.canonicalItemDefinitionUid);if(d.storagePolicy==ItemStoragePolicy.STACKABLE&&!ts.containsKey(d.itemDefinitionUid))sv+=InventoryStackView(PlayerInventoryStack(campaignId,characterUid,d.itemDefinitionUid,legacyQuantity(e),m.mappingVersion,m.provenance),InventoryAuthoritySource.LEGACY_MAPPED,e.evidenceUid) else if(d.storagePolicy==ItemStoragePolicy.UNIQUE_INSTANCE){val uid=m.canonicalItemInstanceUid?:error("Unique mapping lost instance");if(!tu.containsKey(uid)){val i=instance(uid);uv+=InventoryUniqueView(PlayerInventoryUnique(campaignId,characterUid,uid,m.mappingVersion,m.provenance),i,InventoryAuthoritySource.LEGACY_MAPPED,e.evidenceUid)}}};return ReconciledInventory(sv.sortedBy{it.stack.itemDefinitionUid},uv.sortedBy{it.entry.itemInstanceUid},unresolved.sortedBy{it.evidenceUid})}
 private fun mappings(characterUid:String):List<LegacyInventoryMapping>{val o=mutableListOf<LegacyInventoryMapping>();db.rawQuery("SELECT campaign_id,character_uid,legacy_evidence_uid,canonical_item_definition_uid,canonical_item_instance_uid,world_pack_uid,mapping_version,provenance FROM legacy_inventory_mappings WHERE campaign_id=? AND character_uid=?",arrayOf(campaignId,characterUid)).use{c->while(c.moveToNext())o+=LegacyInventoryMapping(c.getString(0),c.getString(1),c.getString(2),c.getString(3),if(c.isNull(4))null else c.getString(4),c.getString(5),c.getLong(6),c.getString(7))};return o}
 private fun legacyQuantity(e:LegacyInventoryEvidence):Long{val q=e.rawFields.entries.firstOrNull{it.key.equals("quantity",true)}?.value;val unit=if(q==null)1L else q.toLongOrNull()?.also{InventoryPolicy.requireQuantity(it)}?:error("Mapped legacy quantity is not a positive integer");return Math.multiplyExact(unit,e.rowCount).also{InventoryPolicy.requireQuantity(it)}}
 private fun definition(uid:String)=definitions().singleOrNull{it.itemDefinitionUid==uid}?:error("Missing item definition $uid")
 private fun instance(uid:String)=db.rawQuery("SELECT campaign_id,item_instance_uid,item_definition_uid,instance_version,provenance FROM item_instances WHERE campaign_id=? AND item_instance_uid=?",arrayOf(campaignId,uid)).use{c->if(!c.moveToFirst())error("Missing item instance $uid");ItemInstance(c.getString(0),c.getString(1),c.getString(2),c.getLong(3),c.getString(4))}
 private fun instanceExists(uid:String)=db.rawQuery("SELECT 1 FROM item_instances WHERE campaign_id=? AND item_instance_uid=? LIMIT 1",arrayOf(campaignId,uid)).use{it.moveToFirst()}
 private fun stackQuantity(c:String,d:String):Long?=db.rawQuery("SELECT quantity FROM player_inventory_stacks WHERE campaign_id=? AND character_uid=? AND item_definition_uid=?",arrayOf(campaignId,c,d)).use{if(it.moveToFirst())it.getLong(0) else null}
 private fun requireCharacter(c:String,p:String,v:Long){require(c.isNotBlank()&&p.isNotBlank()&&v>=1)}
 private fun exists(t:String,c:String,u:String)=db.rawQuery("SELECT 1 FROM $t WHERE $c=? LIMIT 1",arrayOf(u)).use{it.moveToFirst()}
 private fun tableExists(t:String)=db.rawQuery("SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1",arrayOf(t)).use{it.moveToFirst()}
 private fun tableColumns(t:String):List<String>{val o=mutableListOf<String>();db.rawQuery("PRAGMA table_info($t)",null).use{c->val i=c.getColumnIndex("name");while(c.moveToNext())o+=c.getString(i)};return o}
 private fun cursorString(c:Cursor,i:Int):String?=if(c.isNull(i))null else if(c.getType(i)==Cursor.FIELD_TYPE_BLOB)c.getBlob(i).joinToString(""){"%02x".format(it)} else c.getString(i)
 private fun legacyUid(s:String):String="RPGOS-LEGACY-INVENTORY-"+MessageDigest.getInstance("SHA-256").digest(s.toByteArray(StandardCharsets.UTF_8)).joinToString(""){"%02x".format(it)}
 private data class Group(val raw:Map<String,String?>,var count:Long)
}
