package com.rpgos.app

import android.database.Cursor
import android.database.sqlite.SQLiteDatabase
import java.util.UUID

class OwnershipStore(private val db: SQLiteDatabase, private val campaignId: String) {
    init { require(campaignId.isNotBlank()) { "campaignId must not be blank" } }
    fun acquire(record: OwnershipRecord): OwnershipRecord { OwnershipPolicy.validateRecord(record);require(record.campaignId == campaignId);tx{insertRecord(record)};return record }
    fun currentOwnership(asset: OwnedAssetRef, ownershipTypeUid: String? = null): List<OwnershipRecord> { OwnershipPolicy.validateAsset(asset);val typeClause=if(ownershipTypeUid==null)"" else " AND ownership_type_uid=?";val args=mutableListOf(campaignId,asset.assetKindUid,asset.assetUid).apply{if(ownershipTypeUid!=null)add(ownershipTypeUid)};return queryRecords("SELECT $COLUMNS FROM ownership_records WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=? AND record_status='ACTIVE' AND valid_until_order IS NULL$typeClause ORDER BY owner_kind_uid,owner_uid,ownership_record_uid",args.toTypedArray()) }
    fun ownershipAt(asset: OwnedAssetRef, atOrder: Long, ownershipTypeUid: String? = null): List<OwnershipRecord> { OwnershipPolicy.validateAsset(asset);val typeClause=if(ownershipTypeUid==null)"" else " AND ownership_type_uid=?";val args=mutableListOf(campaignId,asset.assetKindUid,asset.assetUid,atOrder.toString(),atOrder.toString()).apply{if(ownershipTypeUid!=null)add(ownershipTypeUid)};return queryRecords("SELECT $COLUMNS FROM ownership_records WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=? AND valid_from_order<=? AND (valid_until_order IS NULL OR ?<valid_until_order)$typeClause ORDER BY owner_kind_uid,owner_uid,ownership_record_uid",args.toTypedArray()) }
    fun history(asset:OwnedAssetRef,ownershipTypeUid:String?=null):List<OwnershipRecord>{OwnershipPolicy.validateAsset(asset);val t=if(ownershipTypeUid==null)"" else " AND ownership_type_uid=?";val a=mutableListOf(campaignId,asset.assetKindUid,asset.assetUid).apply{if(ownershipTypeUid!=null)add(ownershipTypeUid)};return queryRecords("SELECT $COLUMNS FROM ownership_records WHERE campaign_id=? AND asset_kind_uid=? AND asset_uid=?$t ORDER BY valid_from_order,ownership_record_uid",a.toTypedArray())}
    fun ownershipByOwner(owner:OwnershipOwnerRef):List<OwnershipRecord>{OwnershipPolicy.validateOwner(owner);return queryRecords("SELECT $COLUMNS FROM ownership_records WHERE campaign_id=? AND owner_kind_uid=? AND owner_uid=? ORDER BY asset_kind_uid,asset_uid,ownership_type_uid,valid_from_order,ownership_record_uid",arrayOf(campaignId,owner.ownerKindUid,owner.ownerUid))}
    fun fullTransfer(operationUid:String,fromOwner:OwnershipOwnerRef,toOwner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String,effectiveAt:Long,sourceEventUid:String?,provenance:String)=transferShare(operationUid,fromOwner,toOwner,asset,ownershipTypeUid,OwnershipShare.full(),effectiveAt,sourceEventUid,provenance)
    fun transferShare(operationUid:String,fromOwner:OwnershipOwnerRef,toOwner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String,share:OwnershipShare,effectiveAt:Long,sourceEventUid:String?,provenance:String):OwnershipTransferResult{validateOperation(operationUid,fromOwner,asset,ownershipTypeUid,sourceEventUid,provenance);OwnershipPolicy.validateOwner(toOwner);require(fromOwner!=toOwner);return tx{loadTransferOperation(operationUid,fromOwner,toOwner,asset,ownershipTypeUid,share,effectiveAt,sourceEventUid,provenance)?.let{return@tx it};val source=requireCurrentSource(fromOwner,asset,ownershipTypeUid);require(effectiveAt>source.validFrom);require(share.units<=source.share.units);val destination=currentForOwner(toOwner,asset,ownershipTypeUid);val destinationShare=if(destination==null)share else destination.share.add(share);val remaining=source.share.subtract(share);closeRecordCas(source,effectiveAt,sourceEventUid,provenance);if(destination!=null){require(effectiveAt>destination.validFrom);closeRecordCas(destination,effectiveAt,sourceEventUid,provenance)};val sourceSuccessor=remaining?.let{OwnershipRecord(campaignId=campaignId,ownershipRecordUid=newRecordUid(),owner=fromOwner,asset=asset,ownershipTypeUid=ownershipTypeUid,share=it,validFrom=effectiveAt,sourceEventUid=sourceEventUid,supersedesRecordUid=source.ownershipRecordUid,provenance=provenance).also(::insertRecord)};val destinationSuccessor=OwnershipRecord(campaignId=campaignId,ownershipRecordUid=newRecordUid(),owner=toOwner,asset=asset,ownershipTypeUid=ownershipTypeUid,share=destinationShare,validFrom=effectiveAt,sourceEventUid=sourceEventUid,supersedesRecordUid=destination?.ownershipRecordUid?:source.ownershipRecordUid,provenance=provenance).also(::insertRecord);db.execSQL("INSERT INTO ownership_operations(campaign_id,operation_uid,operation_kind,asset_kind_uid,asset_uid,ownership_type_uid,source_record_uid,source_successor_uid,destination_successor_uid,effective_order,source_event_uid,provenance) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)",arrayOf<Any?>(campaignId,operationUid,"TRANSFER",asset.assetKindUid,asset.assetUid,ownershipTypeUid,source.ownershipRecordUid,sourceSuccessor?.ownershipRecordUid,destinationSuccessor.ownershipRecordUid,effectiveAt,sourceEventUid,provenance));OwnershipTransferResult(operationUid,requireRecord(source.ownershipRecordUid),sourceSuccessor,destinationSuccessor)}}
    fun close(operationUid:String,owner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String,effectiveAt:Long,sourceEventUid:String?,provenance:String):OwnershipRecord{validateOperation(operationUid,owner,asset,ownershipTypeUid,sourceEventUid,provenance);return tx{loadCloseOperation(operationUid,owner,asset,ownershipTypeUid,effectiveAt,sourceEventUid,provenance)?.let{return@tx it};val source=requireCurrentSource(owner,asset,ownershipTypeUid);require(effectiveAt>source.validFrom);closeRecordCas(source,effectiveAt,sourceEventUid,provenance);db.execSQL("INSERT INTO ownership_operations(campaign_id,operation_uid,operation_kind,asset_kind_uid,asset_uid,ownership_type_uid,source_record_uid,source_successor_uid,destination_successor_uid,effective_order,source_event_uid,provenance) VALUES(?,?,?,?,?,?,?,NULL,NULL,?,?,?)",arrayOf<Any?>(campaignId,operationUid,"CLOSE",asset.assetKindUid,asset.assetUid,ownershipTypeUid,source.ownershipRecordUid,effectiveAt,sourceEventUid,provenance));requireRecord(source.ownershipRecordUid)}}
    fun registerLegacyMapping(evidenceUid:String,ownershipRecordUid:String,mappingVersion:Long,provenance:String){require(evidenceUid.isNotBlank()&&ownershipRecordUid.isNotBlank()&&provenance.isNotBlank()&&mappingVersion>=1);requireRecord(ownershipRecordUid);db.execSQL("INSERT INTO legacy_ownership_mappings(campaign_id,legacy_evidence_uid,ownership_record_uid,mapping_version,provenance) VALUES(?,?,?,?,?)",arrayOf(campaignId,evidenceUid,ownershipRecordUid,mappingVersion,provenance))}
    private fun validateOperation(operationUid:String,owner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String,sourceEventUid:String?,provenance:String){require(operationUid.isNotBlank());OwnershipPolicy.validateOwner(owner);OwnershipPolicy.validateAsset(asset);require(ownershipTypeUid.isNotBlank()&&provenance.isNotBlank());require(sourceEventUid==null||sourceEventUid.isNotBlank())}
    private fun requireCurrentSource(owner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String)=currentForOwner(owner,asset,ownershipTypeUid)?:error("active source ownership not found")
    private fun currentForOwner(owner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String):OwnershipRecord?=queryRecords("SELECT $COLUMNS FROM ownership_records WHERE campaign_id=? AND owner_kind_uid=? AND owner_uid=? AND asset_kind_uid=? AND asset_uid=? AND ownership_type_uid=? AND record_status='ACTIVE' AND valid_until_order IS NULL ORDER BY ownership_record_uid",arrayOf(campaignId,owner.ownerKindUid,owner.ownerUid,asset.assetKindUid,asset.assetUid,ownershipTypeUid)).singleOrNull()
    private fun closeRecordCas(record:OwnershipRecord,effectiveAt:Long,eventUid:String?,provenance:String){val s=db.compileStatement("UPDATE ownership_records SET valid_until_order=?,closed_by_event_uid=?,record_version=record_version+1,record_status='CLOSED',closure_provenance=? WHERE campaign_id=? AND ownership_record_uid=? AND owner_kind_uid=? AND owner_uid=? AND asset_kind_uid=? AND asset_uid=? AND ownership_type_uid=? AND share_units=? AND record_status='ACTIVE' AND valid_until_order IS NULL AND record_version=?");s.use{var i=1;it.bindLong(i++,effectiveAt);if(eventUid==null)it.bindNull(i++) else it.bindString(i++,eventUid);it.bindString(i++,provenance);it.bindString(i++,campaignId);it.bindString(i++,record.ownershipRecordUid);it.bindString(i++,record.owner.ownerKindUid);it.bindString(i++,record.owner.ownerUid);it.bindString(i++,record.asset.assetKindUid);it.bindString(i++,record.asset.assetUid);it.bindString(i++,record.ownershipTypeUid);it.bindLong(i++,record.share.units);it.bindLong(i,record.recordVersion);require(it.executeUpdateDelete()==1){"stale ownership source: ${record.ownershipRecordUid}"}}}
    private fun insertRecord(r:OwnershipRecord){OwnershipPolicy.validateRecord(r);require(r.campaignId==campaignId);db.execSQL("INSERT INTO ownership_records(campaign_id,ownership_record_uid,owner_kind_uid,owner_uid,asset_kind_uid,asset_uid,ownership_type_uid,share_units,valid_from_order,valid_until_order,source_event_uid,supersedes_record_uid,closed_by_event_uid,record_version,record_status,provenance,closure_provenance,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)",arrayOf<Any?>(r.campaignId,r.ownershipRecordUid,r.owner.ownerKindUid,r.owner.ownerUid,r.asset.assetKindUid,r.asset.assetUid,r.ownershipTypeUid,r.share.units,r.validFrom,r.validUntil,r.sourceEventUid,r.supersedesRecordUid,r.closedByEventUid,r.recordVersion,r.status.name,r.provenance,r.closureProvenance,r.metadataJson))}
    private fun requireRecord(uid:String)=queryRecords("SELECT $COLUMNS FROM ownership_records WHERE campaign_id=? AND ownership_record_uid=?",arrayOf(campaignId,uid)).singleOrNull()?:error("OwnershipRecord not found: $uid")
    private fun loadTransferOperation(operationUid:String,fromOwner:OwnershipOwnerRef,toOwner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String,share:OwnershipShare,effectiveAt:Long,sourceEventUid:String?,provenance:String):OwnershipTransferResult?=db.rawQuery("SELECT asset_kind_uid,asset_uid,ownership_type_uid,source_record_uid,source_successor_uid,destination_successor_uid,effective_order,source_event_uid,provenance FROM ownership_operations WHERE campaign_id=? AND operation_uid=? AND operation_kind='TRANSFER'",arrayOf(campaignId,operationUid)).use{c->if(!c.moveToFirst())return@use null;val storedEvent=if(c.isNull(7))null else c.getString(7);require(c.getString(0)==asset.assetKindUid&&c.getString(1)==asset.assetUid&&c.getString(2)==ownershipTypeUid&&c.getLong(6)==effectiveAt&&storedEvent==sourceEventUid&&c.getString(8)==provenance);val closed=requireRecord(c.getString(3));val ss=if(c.isNull(4))null else requireRecord(c.getString(4));val d=if(c.isNull(5))null else requireRecord(c.getString(5));require(d!=null&&closed.owner==fromOwner&&d.owner==toOwner);require(closed.share.units-(ss?.share?.units?:0L)==share.units);OwnershipTransferResult(operationUid,closed,ss,d)}
    private fun loadCloseOperation(operationUid:String,owner:OwnershipOwnerRef,asset:OwnedAssetRef,ownershipTypeUid:String,effectiveAt:Long,sourceEventUid:String?,provenance:String):OwnershipRecord?=db.rawQuery("SELECT asset_kind_uid,asset_uid,ownership_type_uid,source_record_uid,effective_order,source_event_uid,provenance FROM ownership_operations WHERE campaign_id=? AND operation_uid=? AND operation_kind='CLOSE'",arrayOf(campaignId,operationUid)).use{c->if(!c.moveToFirst())return@use null;val storedEvent=if(c.isNull(5))null else c.getString(5);require(c.getString(0)==asset.assetKindUid&&c.getString(1)==asset.assetUid&&c.getString(2)==ownershipTypeUid&&c.getLong(4)==effectiveAt&&storedEvent==sourceEventUid&&c.getString(6)==provenance);requireRecord(c.getString(3)).also{require(it.owner==owner)}}
    private fun queryRecords(sql:String,args:Array<String>):List<OwnershipRecord>{val out=mutableListOf<OwnershipRecord>();db.rawQuery(sql,args).use{c->while(c.moveToNext())out+=c.toOwnershipRecord()};return out}
    private fun Cursor.toOwnershipRecord()=OwnershipRecord(campaignId=getString(0),ownershipRecordUid=getString(1),owner=OwnershipOwnerRef(getString(2),getString(3)),asset=OwnedAssetRef(getString(4),getString(5)),ownershipTypeUid=getString(6),share=OwnershipShare.ofUnits(getLong(7)),validFrom=getLong(8),validUntil=if(isNull(9))null else getLong(9),sourceEventUid=if(isNull(10))null else getString(10),supersedesRecordUid=if(isNull(11))null else getString(11),closedByEventUid=if(isNull(12))null else getString(12),recordVersion=getLong(13),status=OwnershipRecordStatus.valueOf(getString(14)),provenance=getString(15),closureProvenance=if(isNull(16))null else getString(16),metadataJson=if(isNull(17))null else getString(17))
    private fun newRecordUid()="OWN-${UUID.randomUUID()}"
    private fun<T>tx(block:()->T):T{if(db.inTransaction())return block();db.beginTransaction();return try{val r=block();db.setTransactionSuccessful();r}finally{db.endTransaction()}}
    companion object{private const val COLUMNS="campaign_id,ownership_record_uid,owner_kind_uid,owner_uid,asset_kind_uid,asset_uid,ownership_type_uid,share_units,valid_from_order,valid_until_order,source_event_uid,supersedes_record_uid,closed_by_event_uid,record_version,record_status,provenance,closure_provenance,metadata_json"}
}