package com.rpgos.app

import android.database.sqlite.SQLiteDatabase

const val PHASE14_HARDENING_MIGRATION_ID = "RPGOS-14.1-ASSETS-LIABILITIES-GUARDS"

/** Release-gate guards derived from WORK-062/063/065. */
fun MigrationManager.ensureV14Hardening(db:SQLiteDatabase,campaignId:String){
 ensureV14ContractGuards(db,campaignId)
 db.beginTransaction();try{
  listOf(Triple(ASSET_KIND_INFRASTRUCTURE,"ASSET","Infrastructure"),Triple(ASSET_KIND_RECEIVABLE,"OTHER","Receivable")).forEach{(uid,klass,name)->db.execSQL("INSERT OR IGNORE INTO ownership_asset_kinds(asset_kind_uid,kind_status,provenance) VALUES(?,'ACTIVE','RPGOS-14.1 generic asset namespace')",arrayOf(uid));db.execSQL("INSERT OR IGNORE INTO asset_kind_definitions(asset_kind_uid,asset_class,display_name,definition_status,definition_version,provenance) VALUES(?,?,?,'ACTIVE',1,'RPGOS-14.1 core asset kind')",arrayOf(uid,klass,name))}
  db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS uq_p14_settlement_fin_tx ON obligation_settlements(campaign_id,financial_transaction_uid) WHERE financial_transaction_uid IS NOT NULL")
  db.execSQL("CREATE UNIQUE INDEX IF NOT EXISTS uq_p14_settlement_ownership_op ON obligation_settlements(campaign_id,ownership_operation_uid) WHERE ownership_operation_uid IS NOT NULL")
  listOf("trg_p14_valuation_order_guard","trg_p14_settlement_order_guard","trg_p14_encumbrance_obligation_guard","trg_p14_settled_encumbrance_guard","trg_p14_asset_terminal_relation_guard","trg_p14_ownership_asset_lifecycle_guard","trg_p14_asset_kind_immutable","trg_p14_obligation_type_immutable").forEach{db.execSQL("DROP TRIGGER IF EXISTS $it")}
  db.execSQL("""CREATE TRIGGER trg_p14_valuation_order_guard BEFORE INSERT ON asset_valuations WHEN EXISTS(SELECT 1 FROM asset_valuations v WHERE v.campaign_id=NEW.campaign_id AND v.asset_kind_uid=NEW.asset_kind_uid AND v.asset_uid=NEW.asset_uid AND v.currency_uid=NEW.currency_uid AND v.valuation_type=NEW.valuation_type AND v.effective_order>=NEW.effective_order) BEGIN SELECT RAISE(ABORT,'valuation backdating/conflicting current basis is forbidden; append a later observation'); END""")
  db.execSQL("""CREATE TRIGGER trg_p14_settlement_order_guard BEFORE INSERT ON obligation_settlements WHEN EXISTS(SELECT 1 FROM obligation_settlements s WHERE s.campaign_id=NEW.campaign_id AND s.obligation_uid=NEW.obligation_uid AND s.effective_order>=NEW.effective_order) BEGIN SELECT RAISE(ABORT,'obligation settlement backdating is forbidden'); END""")
  db.execSQL("""CREATE TRIGGER trg_p14_encumbrance_obligation_guard BEFORE INSERT ON asset_encumbrances WHEN COALESCE((SELECT status FROM obligation_status_history s WHERE s.campaign_id=NEW.campaign_id AND s.obligation_uid=NEW.obligation_uid AND s.effective_order<=NEW.valid_from_order ORDER BY effective_order DESC LIMIT 1),'MISSING') NOT IN ('ACTIVE','DEFAULTED') BEGIN SELECT RAISE(ABORT,'encumbrance requires live obligation at effective order'); END""")
  db.execSQL("""CREATE TRIGGER trg_p14_settled_encumbrance_guard BEFORE INSERT ON obligation_status_history WHEN NEW.status='SETTLED' AND EXISTS(SELECT 1 FROM asset_encumbrances e WHERE e.campaign_id=NEW.campaign_id AND e.obligation_uid=NEW.obligation_uid AND e.valid_from_order<=NEW.effective_order AND (e.released_order IS NULL OR NEW.effective_order<e.released_order)) BEGIN SELECT RAISE(ABORT,'release active encumbrance before settling obligation'); END""")
  db.execSQL("""CREATE TRIGGER trg_p14_asset_terminal_relation_guard BEFORE UPDATE ON asset_records WHEN NEW.lifecycle_status<>'ACTIVE' AND (EXISTS(SELECT 1 FROM asset_valuations v WHERE v.campaign_id=OLD.campaign_id AND v.asset_kind_uid=OLD.asset_kind_uid AND v.asset_uid=OLD.asset_uid AND v.effective_order>=NEW.retired_order) OR EXISTS(SELECT 1 FROM asset_encumbrances e WHERE e.campaign_id=OLD.campaign_id AND e.asset_kind_uid=OLD.asset_kind_uid AND e.asset_uid=OLD.asset_uid AND e.valid_from_order<NEW.retired_order AND (e.released_order IS NULL OR NEW.retired_order<e.released_order))) BEGIN SELECT RAISE(ABORT,'asset terminal transition conflicts with later valuation or active encumbrance'); END""")
  db.execSQL("""CREATE TRIGGER trg_p14_ownership_asset_lifecycle_guard BEFORE INSERT ON ownership_records WHEN NEW.asset_kind_uid<>'$OWNERSHIP_ASSET_KIND_ITEM_INSTANCE' AND EXISTS(SELECT 1 FROM asset_records a WHERE a.campaign_id=NEW.campaign_id AND a.asset_kind_uid=NEW.asset_kind_uid AND a.asset_uid=NEW.asset_uid AND (NEW.valid_from_order<a.created_order OR (a.retired_order IS NOT NULL AND NEW.valid_from_order>=a.retired_order))) BEGIN SELECT RAISE(ABORT,'ownership cannot begin outside Phase14 asset lifecycle'); END""")
  db.execSQL("CREATE TRIGGER trg_p14_asset_kind_immutable BEFORE UPDATE ON asset_kind_definitions BEGIN SELECT RAISE(ABORT,'asset kind meaning is immutable; register a new stable kind UID'); END")
  db.execSQL("CREATE TRIGGER trg_p14_obligation_type_immutable BEFORE UPDATE ON obligation_type_definitions BEGIN SELECT RAISE(ABORT,'obligation type meaning is immutable; register a new stable type UID'); END")
  db.execSQL("INSERT OR IGNORE INTO rpgos_schema_migrations(migration_id,applied_at,notes) VALUES('$PHASE14_HARDENING_MIGRATION_ID',strftime('%s','now'),'Phase14 release guards: append-order, evidence uniqueness, terminal relation consistency, ownership lifecycle and immutable type semantics')")
  db.setTransactionSuccessful()
 }finally{db.endTransaction()}
}
