package com.rpgos.app

enum class IntentParseState { PARSED, AMBIGUOUS, UNSUPPORTED, EMPTY }
data class IntentRule(val actionUid:String,val verbs:Set<String>,val requiresTarget:Boolean=false){init{require(actionUid.isNotBlank()&&verbs.isNotEmpty());require(verbs.none{it.isBlank()})}}
data class NormalizedIntent(val campaignUid:String,val actor:CommandActorRef,val actionUid:String,val targetRefs:List<DomainRef>,val methodUid:String?,val timeScopeUid:String?,val rawInput:String,val confidenceUid:String){init{require(campaignUid.isNotBlank()&&actionUid.isNotBlank()&&rawInput.isNotBlank());require(targetRefs.distinct()==targetRefs)}}
sealed interface IntentParseResult{val state:IntentParseState;data class Parsed(val intent:NormalizedIntent):IntentParseResult{override val state=IntentParseState.PARSED};data class Ambiguous(val candidateActionUids:List<String>):IntentParseResult{override val state=IntentParseState.AMBIGUOUS};data class Unsupported(val token:String?):IntentParseResult{override val state=IntentParseState.UNSUPPORTED};data object Empty:IntentParseResult{override val state=IntentParseState.EMPTY}}

class IntentParser(rules:List<IntentRule> = defaultRules){
    private val rules=rules.sortedBy{it.actionUid};init{require(this.rules.map{it.actionUid}.distinct().size==this.rules.size)}
    fun parse(campaignUid:String,actor:CommandActorRef,input:String):IntentParseResult{val clean=input.trim();if(clean.isEmpty())return IntentParseResult.Empty;val tokens=clean.lowercase().split(Regex("\\s+")).filter{it.isNotBlank()};val matches=rules.filter{rule->rule.verbs.any{it in tokens}};if(matches.isEmpty())return IntentParseResult.Unsupported(tokens.firstOrNull());if(matches.size>1)return IntentParseResult.Ambiguous(matches.map{it.actionUid});val rule=matches.single();val targets=tokens.filter{it.startsWith("@")&&it.length>1}.map{raw->val body=raw.drop(1);val split=body.split(':',limit=2);if(split.size==2)DomainRef(split[0].uppercase(),split[1])else DomainRef("ENTITY",body)}.distinct();if(rule.requiresTarget&&targets.isEmpty())return IntentParseResult.Ambiguous(listOf(rule.actionUid));val method=tokens.firstOrNull{it.startsWith("method:")}?.substringAfter(':')?.takeIf{it.isNotBlank()};val time=tokens.firstOrNull{it.startsWith("time:")}?.substringAfter(':')?.takeIf{it.isNotBlank()};return IntentParseResult.Parsed(NormalizedIntent(campaignUid,actor,rule.actionUid,targets,method,time,clean,"RULE_EXACT"))}
    companion object{val defaultRules=listOf(IntentRule("LOOK",setOf("look","inspect","sprawdź","obejrzyj")),IntentRule("MOVE",setOf("move","go","idź","rusz"),true),IntentRule("TALK",setOf("talk","ask","porozmawiaj","zapytaj"),true),IntentRule("ATTACK",setOf("attack","strike","atakuj","uderz"),true),IntentRule("USE",setOf("use","użyj"),true),IntentRule("WAIT",setOf("wait","czekaj")),IntentRule("STATUS",setOf("status","stan")))}
}

enum class PlanStepPriority { REQUIRED, SAFETY, QUALITY, OPTIONAL }
data class PlannerCapabilityRule(val actionUid:String,val providerUid:String,val operationUid:String,val priority:PlanStepPriority,val requiresTarget:Boolean=false){init{require(actionUid.isNotBlank()&&providerUid.isNotBlank()&&operationUid.isNotBlank())}}
data class TurnPlanStep(val stepUid:String,val request:StructuredRetrievalRequest,val priority:PlanStepPriority)
data class TurnPlan(val planUid:String,val campaignUid:String,val intent:NormalizedIntent,val audience:AudienceContext,val purpose:PurposeContext,val steps:List<TurnPlanStep>){init{require(planUid.isNotBlank()&&intent.campaignUid==campaignUid&&audience.campaignUid==campaignUid&&purpose.campaignUid==campaignUid);require(steps.map{it.stepUid}.distinct().size==steps.size)}}
class TurnPlanner(private val rules:List<PlannerCapabilityRule>){
    fun plan(intent:NormalizedIntent,audience:AudienceContext,purpose:PurposeContext,atOrder:Long?=null):TurnPlan{require(intent.campaignUid==audience.campaignUid&&intent.campaignUid==purpose.campaignUid){"RPGOS-P44:CROSS_CAMPAIGN"};val applicable=rules.filter{it.actionUid==intent.actionUid}.sortedWith(compareBy<PlannerCapabilityRule>{it.priority.ordinal}.thenBy{it.providerUid}.thenBy{it.operationUid});val steps=applicable.mapIndexedNotNull{i,rule->val target=intent.targetRefs.firstOrNull();if(rule.requiresTarget&&target==null)return@mapIndexedNotNull null;val filters=buildMap{target?.let{put("subject_kind_uid",it.kindUid);put("subject_uid",it.uid)}};val request=StructuredRetrievalRequest("REQ:${intent.actionUid}:$i",intent.campaignUid,rule.providerUid,rule.operationUid,filters,50,audience,purpose,atOrder);TurnPlanStep("STEP:${intent.actionUid}:$i",request,rule.priority)};return TurnPlan("PLAN:${intent.campaignUid}:${intent.actor.actorUid}:${intent.actionUid}:${steps.joinToString{it.stepUid}}",intent.campaignUid,intent,audience,purpose,steps)}
}
