package com.rpgos.app

import android.database.sqlite.SQLiteDatabase
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.File

@RunWith(RobolectricTestRunner::class) @Config(sdk=[34])
class InventoryPersistenceTest{
 private lateinit var f:File
 @Before fun setUp(){f=File.createTempFile("inv-",".db");f.delete()};@After fun tearDown(){f.delete()}
 private fun db()=SQLiteDatabase.openOrCreateDatabase(f,null);private fun fail(block:()->Unit){var x=false;try{block()}catch(_:Throwable){x=true};assertTrue(x)}
 private fun s(uid:String,p:String="W",n:String=uid)=ItemDefinition(uid,p,uid.lowercase(),n,storagePolicy=ItemStoragePolicy.STACKABLE,provenance="pack")
 private fun u(uid:String,p:String="W",n:String=uid)=ItemDefinition(uid,p,uid.lowercase(),n,storagePolicy=ItemStoragePolicy.UNIQUE_INSTANCE,provenance="pack")
 @Test fun definitionsStacksUniqueAndQuantityContracts(){db().use{d->CurrentSchema.ensure(d,"C");val x=InventoryStore(d,"C");x.registerDefinitions("W",listOf(s("S"),u("U")));fail{x.registerDefinitions("W",listOf(s("S")))};x.addStack("P","S",2,"a");x.addStack("P","S",3,"b");assertEquals(5L,x.typedStacks("P").single().quantity);fail{x.addStack("P","S",0,"z")};fail{x.addStack("P","S",-1,"n")};x.removeStack("P","S",5,"zero");assertTrue(x.typedStacks("P").isEmpty());x.addStack("P","S",Long.MAX_VALUE,"m");fail{x.addStack("P","S",1,"overflow")};assertEquals(Long.MAX_VALUE,x.typedStacks("P").single().quantity);x.createInstance(ItemInstance("C","I1","U",provenance="i"));x.createInstance(ItemInstance("C","I2","U",provenance="i"));x.addUnique("P","I1","a");x.addUnique("P","I2","a");assertEquals(2,x.typedUnique("P").size);fail{x.addUnique("Q","I1","steal")};fail{x.addStack("P","U",2,"bad")}}}
 @Test fun sameNameCrossPackCampaignPlayerIsolation(){db().use{d->CurrentSchema.ensure(d,"A");val a=InventoryStore(d,"A");a.registerDefinitions("A",listOf(s("A1","A","Same")));a.registerDefinitions("B",listOf(s("B1","B","Same")));a.addStack("P","A1",1,"a");a.addStack("Q","B1",2,"q");assertEquals(1,a.typedStacks("P").size);assertEquals(1,a.typedStacks("Q").size);assertTrue(InventoryStore(d,"B").typedStacks("P").isEmpty())}}
 @Test fun legacyIsUnresolvedUntilExplicitMappingAndBytesRemain(){db().use{d->d.execSQL("CREATE TABLE character_inventory(entity_uid TEXT,item_name TEXT,quantity INTEGER,notes TEXT)");d.execSQL("INSERT INTO character_inventory VALUES('P','Same',3,'raw')");CurrentSchema.ensure(d,"C");val x=InventoryStore(d,"C");x.registerDefinitions("W",listOf(s("CAN","W","Same")));val e=x.reconciled("P").unresolvedLegacy.single();assertEquals("Same",e.itemName);fail{x.registerLegacyMappings("BAD",listOf(LegacyInventoryMapping("C","P",e.evidenceUid,"CAN",worldPackUid="BAD",provenance="bad")))};x.registerLegacyMappings("W",listOf(LegacyInventoryMapping("C","P",e.evidenceUid,"CAN",worldPackUid="W",provenance="map")));val r=x.reconciled("P");assertEquals(3L,r.stacks.single().stack.quantity);assertTrue(r.unresolvedLegacy.isEmpty());d.rawQuery("SELECT item_name,quantity,notes FROM character_inventory WHERE entity_uid='P'",null).use{c->c.moveToFirst();assertEquals("Same",c.getString(0));assertEquals(3,c.getInt(1));assertEquals("raw",c.getString(2))}}}
 @Test fun mixedTypedAndLegacyNeverSilentNameMerge(){db().use{d->d.execSQL("CREATE TABLE character_inventory(entity_uid TEXT,item_name TEXT)");d.execSQL("INSERT INTO character_inventory VALUES('P','Same')");CurrentSchema.ensure(d,"C");val x=InventoryStore(d,"C");x.registerDefinitions("W",listOf(s("CAN","W","Same")));x.addStack("P","CAN",5,"typed");val r=x.reconciled("P");assertEquals(1,r.stacks.size);assertEquals(1,r.unresolvedLegacy.size);assertEquals(InventoryAuthoritySource.TYPED,r.stacks.single().authoritySource)}}
 @Test fun uniqueLegacyNeedsExplicitInstance(){db().use{d->d.execSQL("CREATE TABLE character_inventory(entity_uid TEXT,item_name TEXT)");d.execSQL("INSERT INTO character_inventory VALUES('P','Relic')");CurrentSchema.ensure(d,"C");val x=InventoryStore(d,"C");x.registerDefinitions("W",listOf(u("U")));x.createInstance(ItemInstance("C","I","U",provenance="i"));val e=x.legacyEvidence("P").single();fail{x.registerLegacyMappings("W",listOf(LegacyInventoryMapping("C","P",e.evidenceUid,"U",worldPackUid="W",provenance="bad")))};x.registerLegacyMappings("W",listOf(LegacyInventoryMapping("C","P",e.evidenceUid,"U","I","W",provenance="ok")));assertEquals("I",x.reconciled("P").uniqueItems.single().entry.itemInstanceUid)}}
 @Test fun scaleReopenMigrationAndIntegrity(){db().use{d->CurrentSchema.ensure(d,"C");CurrentSchema.ensure(d,"C");val x=InventoryStore(d,"C");val defs=(0..1004).map{s("S$it")};x.registerDefinitions("W",defs);defs.forEach{x.addStack("P",it.itemDefinitionUid,1,"bulk")};assertEquals(1005,x.typedStacks("P").size);assertEquals(0,scalar(d,"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name IN ('player_equipment','ownership_records_v2')"));assertEquals(1,scalar(d,"SELECT COUNT(*) FROM rpgos_schema_migrations WHERE migration_id='$PHASE10_MIGRATION_ID'"));d.rawQuery("PRAGMA integrity_check",null).use{c->c.moveToFirst();assertEquals("ok",c.getString(0))};d.rawQuery("PRAGMA foreign_key_check",null).use{c->assertFalse(c.moveToFirst())}};SQLiteDatabase.openDatabase(f.absolutePath,null,SQLiteDatabase.OPEN_READWRITE).use{d->CurrentSchema.ensure(d,"C");assertEquals(1005,InventoryStore(d,"C").typedStacks("P").size)}}
 private fun scalar(d:SQLiteDatabase,q:String)=d.rawQuery(q,null).use{c->c.moveToFirst();c.getInt(0)}
}
