package com.rpgos.app

import android.database.sqlite.SQLiteDatabase
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.File

@RunWith(RobolectricTestRunner::class)
@Config(sdk=[34])
class Phase9PersistenceTest {
    private lateinit var dbFile:File
    @Before fun setUp(){dbFile=File.createTempFile("rpgos-phase9-",".db");dbFile.delete()}
    @After fun tearDown(){dbFile.delete()}
    private fun open()=SQLiteDatabase.openOrCreateDatabase(dbFile,null)
    private fun fail(block:()->Unit){var failed=false;try{block()}catch(_:Throwable){failed=true};assertTrue(failed)}
    private fun origin(uid:String,pack:String="W",key:String=uid.lowercase(),name:String="Same")=OriginDefinition(uid,pack,key,name,"generic",provenance="pack")
    private fun feature(uid:String,pack:String="W",key:String=uid.lowercase(),name:String="Same")=InnateFeatureDefinition(uid,pack,key,name,"generic",provenance="pack")
    private fun path(uid:String,pack:String="W")=EvolutionPathDefinition(uid,pack,uid.lowercase(),uid,provenance="pack")
    private fun stage(uid:String,path:String,pack:String="W")=EvolutionStageDefinition(uid,path,pack,uid.lowercase(),uid,provenance="pack")
    private fun form(uid:String,pack:String="W",group:String?=null)=FormDefinition(uid,pack,uid.lowercase(),uid,exclusiveGroupUid=group,provenance="pack")

    @Test fun definitionsOwnershipDuplicatesSameLabelAndPlayerIsolation(){open().use{db->MigrationManager().ensureV9(db,"C");val s=Phase9Store(db,"C");s.registerOrigins("W",listOf(origin("O1")));fail{s.registerOrigins("W",listOf(origin("O1",key="other")))};fail{s.registerOrigins("OTHER",listOf(origin("O2",pack="W")))};s.registerOrigins("OTHER",listOf(origin("O2",pack="OTHER",name="Same")));assertEquals(2,s.origins().size);s.registerInnateFeatures("W",listOf(feature("F")));s.saveOrigin(PlayerOrigin("C","P","O1","PRIMARY",provenance="typed"));s.grantInnateFeature(PlayerInnateFeature("C","P","F",provenance="typed"));assertEquals(1,s.playerOrigins("P").size);assertEquals(1,s.playerInnateFeatures("P").size);assertTrue(s.playerOrigins("Q").isEmpty());assertTrue(Phase9Store(db,"OTHER-CAMPAIGN").playerOrigins("P").isEmpty());fail{s.saveOrigin(PlayerOrigin("OTHER-CAMPAIGN","P","O1","PRIMARY",provenance="x"))}}}

    @Test fun unlockActiveDeactivateAndExclusiveForms(){open().use{db->db.execSQL("PRAGMA foreign_keys=ON");MigrationManager().ensureV9(db,"C");val s=Phase9Store(db,"C");s.registerForms("W",listOf(form("A",group="G"),form("B",group="G"),form("C")));fail{s.activateForm(PlayerActiveForm("C","P","A",provenance="x"))};s.unlockForm(PlayerFormUnlock("C","P","A",provenance="unlock"));s.unlockForm(PlayerFormUnlock("C","P","B",provenance="unlock"));assertTrue(s.activeForms("P").isEmpty());s.activateForm(PlayerActiveForm("C","P","A",provenance="on"));assertEquals(listOf("A"),s.activeForms("P").map{it.formUid});fail{s.activateForm(PlayerActiveForm("C","P","B",provenance="conflict"))};s.deactivateForm("P","A");assertTrue(s.activeForms("P").isEmpty());assertEquals(setOf("A","B"),s.formUnlocks("P").map{it.formUid}.toSet());s.activateForm(PlayerActiveForm("C","P","B",provenance="on2"));assertEquals("B",s.activeForms("P").single().formUid)}}

    @Test fun explicitEvolutionTransitionsOnlyAndHistoryPersists(){open().use{db->MigrationManager().ensureV9(db,"C");val s=Phase9Store(db,"C");s.registerEvolutionPaths("W",listOf(path("P1"),path("P2")));s.registerEvolutionStages("W",listOf(stage("A","P1"),stage("B","P1"),stage("X","P2")));fail{s.registerEvolutionTransitions("W",listOf(EvolutionTransitionDefinition("BAD","W","A","X",provenance="pack")))};s.registerEvolutionTransitions("W",listOf(EvolutionTransitionDefinition("ENTRY-A","W",null,"A",provenance="pack"),EvolutionTransitionDefinition("AB","W","A","B",provenance="pack")));fail{s.transitionEvolution("PLAYER","MISSING","bad")};s.transitionEvolution("PLAYER","ENTRY-A","start");fail{s.transitionEvolution("PLAYER","ENTRY-A","replay")};s.transitionEvolution("PLAYER","AB","advance");assertEquals("B",s.evolutionStates("PLAYER").single().currentStageUid);assertEquals(setOf("A","B"),s.attainedStages("PLAYER").map{it.stageUid}.toSet());assertEquals("ENTRY-A",s.attainedStages("PLAYER").single{it.stageUid=="A"}.attainedViaTransitionUid);fail{s.transitionEvolution("PLAYER","AB","rollback-not-a-transition")}}}

    @Test fun legacyLabelsGrantNothingExplicitMappingCanonicalizesOnceAndBytesRemain(){open().use{db->db.execSQL("CREATE TABLE character_status_snapshot(entity_uid TEXT PRIMARY KEY,clan_uid TEXT,race TEXT,bloodline TEXT,evolution_stage TEXT,form TEXT)");db.execSQL("INSERT INTO character_status_snapshot VALUES('P','C-legacy','Race Legacy','Blood Legacy','Stage Legacy','Form Legacy')");val before=dump(db);MigrationManager().ensureV9(db,"C");val s=Phase9Store(db,"C");s.registerOrigins("W",listOf(origin("O")));s.registerInnateFeatures("W",listOf(feature("F")));assertTrue(s.playerOrigins("P").isEmpty());assertTrue(s.playerInnateFeatures("P").isEmpty());assertEquals(5,s.legacyEvidence("P").size);assertTrue(s.reconcileLegacy("P","W").all{!it.canonical});s.registerLegacyMappings("W",listOf(LegacyPhase9Mapping("W","bloodline","Blood Legacy",LegacyPhase9TargetKind.INNATE_FEATURE,"F",provenance="explicit")));s.applyLegacyMappings("P","W");s.applyLegacyMappings("P","W");assertEquals(listOf("F"),s.playerInnateFeatures("P").map{it.featureUid});assertEquals(before,dump(db));fail{s.registerLegacyMappings("OTHER",listOf(LegacyPhase9Mapping("OTHER","race","Race Legacy",LegacyPhase9TargetKind.ORIGIN,"O",provenance="hijack")))}}}

    @Test fun temporaryFormUsesGenericModifiersAndNeverRewritesBaseDomains(){open().use{db->MigrationManager().ensureV9(db,"C");val sr=StatResourceStore(db,"C");sr.registerStatDefinitions("W",listOf(StatDefinition("STAT","stat","generic",worldPackUid="W")));sr.savePlayerStat(PlayerStat("C","P","STAT",10.0));val sk=SkillStore(db,"C");sk.registerDefinitions("W",listOf(SkillDefinition("SK","W","sk","Skill","generic",provenance="pack")));sk.savePlayerSkill(PlayerSkill("C","P","SK",20.0,provenance="base"));val te=TechniqueStore(db,"C");te.registerDefinitions("W",listOf(TechniqueDefinition("TE","W","te","Technique","generic",provenance="pack")));te.savePlayerTechnique(PlayerTechnique("C","P","TE",30.0,provenance="base"));val profiles=ProgressionProfileStore(db,"C");profiles.registerDomains("W",listOf(ProgressionDomainDefinition("D","W","d","D","generic",definitionVersion=1,provenance="pack")));profiles.saveTalent(TalentEntry("C","P","D",0.7,provenance="talent"));profiles.savePotential(PotentialEntry("C","P","D","growth",0.8,provenance="potential"));val p9=Phase9Store(db,"C");p9.registerForms("W",listOf(form("FORM")));p9.registerFormModifierBindings("W",listOf(FormModifierBinding("M1","W","FORM","STAT",ModifierTargetKind.STAT_EFFECTIVE,ModifierOperation.ADD_FLAT,5.0,provenance="form"),FormModifierBinding("M2","W","FORM","SK",ModifierTargetKind.SKILL_EFFECTIVE,ModifierOperation.ADD_FLAT,6.0,provenance="form"),FormModifierBinding("M3","W","FORM","TE",ModifierTargetKind.TECHNIQUE_EFFECTIVE,ModifierOperation.ADD_FLAT,7.0,provenance="form")));p9.unlockForm(PlayerFormUnlock("C","P","FORM",provenance="unlock"));p9.activateForm(PlayerActiveForm("C","P","FORM",provenance="on"));val mods=ModifierStore(db,"C").modifiers("P");assertEquals(3,mods.count{it.sourceType=="PHASE9_FORM"&&it.sourceActive});assertEquals(10.0,sr.playerStats("P").single().baseValue,0.0);assertEquals(20.0,sk.playerSkills("P").single().baseMastery,0.0);assertEquals(30.0,te.playerTechniques("P").single().baseMastery,0.0);assertEquals(0.7,profiles.talentProfile("P").entries.single().baseValue,0.0);assertEquals(0.8,profiles.potentialProfile("P").entries.single().baseValue,0.0);p9.deactivateForm("P","FORM");assertTrue(ModifierStore(db,"C").modifiers("P").filter{it.sourceType=="PHASE9_FORM"}.all{!it.sourceActive});assertEquals(10.0,sr.playerStats("P").single().baseValue,0.0);assertEquals(20.0,sk.playerSkills("P").single().baseMastery,0.0);assertEquals(30.0,te.playerTechniques("P").single().baseMastery,0.0)}}

    @Test fun currentSchemaV9IdempotentReopenAndThousandEntriesNoTruncationIntegrityFk(){open().use{db->db.execSQL("PRAGMA foreign_keys=ON");CurrentSchema.ensure(db,"C");CurrentSchema.ensure(db,"C");assertEquals(1,scalar(db,"SELECT COUNT(*) FROM rpgos_schema_migrations WHERE migration_id='$PHASE9_MIGRATION_ID'"));val s=Phase9Store(db,"C");val defs=(0 until 1005).map{i->feature("F%04d".format(i),key="k%04d".format(i),name="Feature $i")};s.registerInnateFeatures("W",defs);db.beginTransaction();try{defs.forEach{s.grantInnateFeature(PlayerInnateFeature("C","P",it.featureUid,provenance="bulk"))};db.setTransactionSuccessful()}finally{db.endTransaction()};assertEquals(1005,s.innateFeatures("W").size);assertEquals(1005,s.playerInnateFeatures("P").size);db.rawQuery("PRAGMA integrity_check",null).use{c->assertTrue(c.moveToFirst());assertEquals("ok",c.getString(0))};db.rawQuery("PRAGMA foreign_key_check",null).use{c->assertFalse(c.moveToFirst())}}
        open().use{db->CurrentSchema.ensure(db,"C");assertEquals(1005,Phase9Store(db,"C").playerInnateFeatures("P").size)}}

    @Test fun playerStateContextContainsTypedPhase9AlongsideUnresolvedLegacy(){open().use{db->db.execSQL("CREATE TABLE character_status_snapshot(entity_uid TEXT PRIMARY KEY,race TEXT)");db.execSQL("INSERT INTO character_status_snapshot VALUES('P','legacy-race')");CurrentSchema.ensure(db,"C");ActivePlayerStore(db,"C").set("P");val s=Phase9Store(db,"C");s.registerOrigins("W",listOf(origin("O")));s.saveOrigin(PlayerOrigin("C","P","O","PRIMARY",provenance="typed"));val state=PlayerStateStore(db,"C").load()!!;val phase9=state.persistent["phase9"] as Map<*,*>;assertEquals(1,(phase9["origins"] as List<*>).size);assertEquals(1,(phase9["unresolved_legacy"] as List<*>).size);assertEquals("legacy-race",state.persistent["legacy_status.race"])} }

    private fun scalar(db:SQLiteDatabase,sql:String)=db.rawQuery(sql,null).use{c->assertTrue(c.moveToFirst());c.getInt(0)}
    private fun dump(db:SQLiteDatabase):List<List<String?>>{val out=mutableListOf<List<String?>>();db.rawQuery("SELECT entity_uid,clan_uid,race,bloodline,evolution_stage,form FROM character_status_snapshot ORDER BY entity_uid",null).use{c->while(c.moveToNext())out+=List(c.columnCount){i->if(c.isNull(i))null else c.getString(i)}};return out}
}