package com.rpgos.app

import org.junit.Assert.*
import org.junit.Test

class Phase32TruthLayerEnforcementTest {
 @Test fun registryCoversRequiredFamiliesAndFailsClosed(){ RuntimeTruthLayerRegistry.validateCanonicalInventory(); listOf("CAMPAIGN_TRUTH","ACTIVE_PLAYER_IDENTITY","BASE_STATS_RESOURCES","SKILLS_TECHNIQUES","INNATE_EVOLUTION","INVENTORY","EQUIPMENT_LOADOUT","OWNERSHIP_HISTORY","FINANCE_AUTHORITY","FINANCE_BALANCE_PROJECTION","DEVELOPMENT_PROJECTS","MODIFIER_INPUTS","RESOLVED_EFFECTIVE_VALUES","TURN_RECEIPTS","EVENT_STORE","CAUSAL_GRAPH","CHARACTER_PANEL_SNAPSHOT_V2","PLAYER_SNAPSHOT_PROFILES","CONTEXT_BUNDLE","CHAPTER_MANIFESTS_SUMMARIES","REBUILDABLE_INDEXES_MATERIALIZATIONS","UI_STATE","BACKUP_PACKAGES","SCHEMA_MIGRATION_REPAIR").forEach{assertNotNull(RuntimeTruthLayerRegistry.requireFamily(it))}; assertTrue(runCatching{RuntimeTruthLayerRegistry.requireFamily("UNKNOWN")}.isFailure) }
 @Test fun nonAuthorityCapabilitiesCannotWriteAuthority(){ listOf(RuntimeMutationCapability.DERIVED_REBUILD,RuntimeMutationCapability.CACHE_REBUILD,RuntimeMutationCapability.PRESENTATION_ONLY).forEach{c->assertTrue(runCatching{RuntimeTruthLayerRegistry.requireAuthoritativeMutation("CAMPAIGN_TRUTH",c)}.isFailure)}; RuntimeTruthLayerRegistry.requireAuthoritativeMutation("CAMPAIGN_TRUTH",RuntimeMutationCapability.CANONICAL_TURN) }
 @Test fun gameplayCannotAcquireAdministrativeAuthority(){ assertTrue(runCatching{RuntimeTruthLayerRegistry.requireGameplayCapability(RuntimeMutationCapability.ADMINISTRATIVE)}.isFailure); RuntimeTruthLayerRegistry.requireGameplayCapability(RuntimeMutationCapability.CANONICAL_TURN) }
 @Test fun establishedReadModelsRemainDerived(){ assertEquals(setOf(RuntimeTruthLayer.DERIVED_PRESENTATION),RuntimeTruthLayerRegistry.requireFamily("CHARACTER_PANEL_SNAPSHOT_V2").layers); assertEquals(setOf(RuntimeTruthLayer.DERIVED_PROJECTION),RuntimeTruthLayerRegistry.requireFamily("PLAYER_SNAPSHOT_PROFILES").layers); assertEquals(CharacterPanelSnapshotClassification.DERIVED_PRESENTATION,CharacterPanelSnapshotClassification.valueOf("DERIVED_PRESENTATION")); assertEquals(PlayerSnapshotClassification.DERIVED_PROJECTION,PlayerSnapshotClassification.valueOf("DERIVED_PROJECTION")) }
 @Test fun everyPlayerSnapshotProfileIsDerivedProjection(){ PlayerSnapshotProfile.values().forEach{ assertEquals(RuntimeTruthLayer.DERIVED_PROJECTION,RuntimeTruthLayerRegistry.requireFamily("PLAYER_SNAPSHOT_PROFILES").layers.single()) } }
 @Test fun appendOnlyIsNotSynonymForGenericEvidence(){ assertTrue(RuntimeTruthLayerRegistry.requireFamily("FINANCE_AUTHORITY").isAuthoritative); assertTrue(RuntimeTruthLayerRegistry.requireFamily("OWNERSHIP_HISTORY").isAuthoritative); assertFalse(RuntimeTruthLayerRegistry.requireFamily("EVENT_STORE").isAuthoritative); assertFalse(RuntimeTruthLayerRegistry.requireFamily("CAUSAL_GRAPH").isAuthoritative) }
 @Test fun unknownPersistentFamilyCannotDefaultToAuthority(){ assertTrue(runCatching{RuntimeTruthLayerRegistry.requireClassifiedTable("future_unclassified_table")}.isFailure) }
}
