package com.rpgos.app

import android.database.sqlite.SQLiteDatabase
import org.junit.Assert.*
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class)
@Config(sdk = [35])
class PlayerDomainEngineTest {
    private val actor = CommandActorRef("PLAYER", "P1")
    private val commandRegistry = PlayerCommandKindRegistry.core()

    @Test fun p18Hotfix01_noFullCommandToChangeSetComponentBypass() { val m=PlayerResolutionComponent::class.java.declaredMethods.filter{it.name.startsWith("resolve")}; assertTrue(m.isNotEmpty()); m.forEach{assertNotEquals(PlayerChangeSet::class.java,it.returnType)}; assertTrue(m.any{PlayerResolutionComponentOutcome::class.java.isAssignableFrom(it.returnType)}); try{Class.forName("com.rpgos.app.PlayerCommandResolver"); fail("legacy public PlayerCommandResolver must not exist")}catch(_:ClassNotFoundException){} }
    @Test fun p18Hotfix02_canonicalPublicEntryIsPlayerDomainEngine() { val m=PlayerDomainEngine::class.java.methods.filter{it.name=="resolve"}; assertEquals(1,m.size); assertEquals(PlayerResolutionOutcome::class.java,m.single().returnType) }
    @Test fun p18Hotfix03_componentReturnsTypedDraftNotFinalProposal() { val o=StatComponent(3).resolve(train(),context()) as PlayerResolutionComponentOutcome.Resolved; assertEquals(1,o.draft.changes.size); assertNotEquals(PlayerChangeSet::class.java.name,o.draft.javaClass.name) }
    @Test fun p18Hotfix04_domainRejectionIsTypedAndDistinctFromStructuralFault() { val r=engine(RejectingTrainComponent()).resolve(train(),context()) as PlayerResolutionOutcome.Rejected; assertEquals(PlayerResolutionRejectionReason.DOMAIN_REJECTED,r.rejection.reason); assertEquals("RPGOS-RESOLUTION-REJECTION:DOMAIN_REJECTED",r.rejection.reason.reasonUid); failsEngine("DUPLICATE_COMMAND_RESOLUTION_COMPONENT"){PlayerResolutionComponentRegistry.of(listOf(StatComponent(1),StatComponent(2)))} }
    @Test fun p18Hotfix05_hiddenWriterCannotBeRegisteredAsSupportedComponentState() { val db=authorityDb(); try{failsEngine("UNSAFE_RESOLUTION_COMPONENT_STATE"){PlayerResolutionComponentRegistry.of(listOf(DbCapturingTrainComponent(db)))}; assertEquals(7L,authorityValue(db))}finally{db.close()} }
    @Test fun p18Hotfix06_resolutionContextIsImmutableDataOnly() { val c=context(); val bad=listOf("SQLite","Room","Dao","Store","Repository","Transaction","StatePatch","Random","Clock"); PlayerResolutionContext::class.java.declaredFields.forEach{f->bad.forEach{t->assertFalse("context field ${f.name} leaked $t",f.type.name.contains(t,true))}}; try{ @Suppress("UNCHECKED_CAST") (c.knownReferences as MutableSet<CampaignScopedDomainRef>).clear(); fail("knownReferences must be immutable") }catch(_:UnsupportedOperationException){}; try{ @Suppress("UNCHECKED_CAST") (c.dependencyVersions as MutableMap<String,String>).clear(); fail("dependencyVersions must be immutable") }catch(_:UnsupportedOperationException){} }
    @Test fun p18Hotfix07_sideEffectBeforeFailureAttackIsRejectedAtRegistration() { val db=authorityDb(); try{val b=authorityValue(db); failsEngine("UNSAFE_RESOLUTION_COMPONENT_STATE"){engine(DbCapturingTrainComponent(db))}; assertEquals(b,authorityValue(db))}finally{db.close()} }
    @Test fun p18Hotfix08_mutableComponentAliasIsRejectedAtRegistration() { val c=MutableTrainComponent(1); failsEngine("MUTABLE_RESOLUTION_COMPONENT_STATE"){PlayerResolutionComponentRegistry.of(listOf(c))}; c.delta=9; assertEquals(9L,c.delta) }
    @Test fun p18Hotfix09_sameCommandAndContextAreDeterministic() { val e=engine(StatComponent(3)); val a=resolved(e.resolve(train(),context())); val b=resolved(e.resolve(train(),context())); assertEquals(a,b); assertEquals(PlayerChangeSetCodec.fingerprint(a),PlayerChangeSetCodec.fingerprint(b)) }
    @Test fun p18Hotfix10_sameExplicitEntropyProducesSameResultAndEvidence() { val e=engine(EntropyTrainComponent()); val a=e.resolve(train(),context(entropy=ResolutionEntropyEvidence("TEST-SEED",7))) as PlayerResolutionOutcome.Resolved; val b=e.resolve(train(),context(entropy=ResolutionEntropyEvidence("TEST-SEED",7))) as PlayerResolutionOutcome.Resolved; assertEquals(a,b); assertEquals(7L,a.evidence.entropy.exactValue) }
    @Test fun p18Hotfix11_differentExplicitEntropyCanChangeProposalAndEvidence() { val e=engine(EntropyTrainComponent()); val a=e.resolve(train(),context(entropy=ResolutionEntropyEvidence("TEST-SEED",7))) as PlayerResolutionOutcome.Resolved; val b=e.resolve(train(),context(entropy=ResolutionEntropyEvidence("TEST-SEED",8))) as PlayerResolutionOutcome.Resolved; assertNotEquals(a.proposal,b.proposal); assertNotEquals(a.evidence,b.evidence); assertEquals(7L,(a.proposal.changes.single().payload as StatChange).delta.units); assertEquals(8L,(b.proposal.changes.single().payload as StatChange).delta.units) }
    @Test fun p18Hotfix12_noHiddenEntropyCapabilityOnEngineOrContext() { val bad=listOf("Random","Clock","UUID","Instant"); listOf(PlayerDomainEngine::class.java,PlayerResolutionContext::class.java,ResolutionEntropyEvidence::class.java).flatMap{it.declaredFields.toList()}.forEach{f->bad.forEach{assertFalse(f.type.name.contains(it,true))}}; assertTrue(ResolutionEntropyEvidence::class.java.declaredFields.any{it.name=="exactValue"}) }
    @Test fun p18Hotfix13_unknownOrWrongCampaignReferenceIsTypedRejection() { val g=train().copy(payload=TrainCommandPayload(DomainRef("PLAYER","GHOST-NOT-IN-CAMPAIGN"),10,"METHOD")); val u=engine(StatComponent(1)).resolve(g,context()) as PlayerResolutionOutcome.Rejected; assertEquals(PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,u.rejection.reason); val w=engine(StatComponent(1)).resolve(g,context(extraRefs=setOf(scoped("OTHER","PLAYER","GHOST-NOT-IN-CAMPAIGN")))) as PlayerResolutionOutcome.Rejected; assertEquals(PlayerResolutionRejectionReason.WRONG_CAMPAIGN_REFERENCE,w.rejection.reason) }
    @Test fun p18Hotfix14_validSameCampaignReferenceIsAccepted() { assertTrue(engine(StatComponent(1)).resolve(train(),context()) is PlayerResolutionOutcome.Resolved) }
    @Test fun p18Hotfix15_referenceValidationWritesNothing() { val db=authorityDb(); try{val b=authorityValue(db); val g=train().copy(payload=TrainCommandPayload(DomainRef("PLAYER","GHOST-NOT-IN-CAMPAIGN"),10,"METHOD")); assertTrue(engine(StatComponent(1)).resolve(g,context()) is PlayerResolutionOutcome.Rejected); assertEquals(b,authorityValue(db))}finally{db.close()} }
    @Test fun p18Hotfix16_componentRejectionCausesZeroAuthoritativeMutation() { val db=authorityDb(); try{val b=authorityValue(db); assertTrue(engine(RejectingTrainComponent()).resolve(train(),context()) is PlayerResolutionOutcome.Rejected); assertEquals(b,authorityValue(db))}finally{db.close()} }
    @Test fun p18Hotfix17_componentThrowCausesZeroAuthoritativeMutation() { val db=authorityDb(); try{val b=authorityValue(db); failsEngine("RESOLUTION_COMPONENT_FAILURE"){engine(ThrowingTrainComponent()).resolve(train(),context())}; assertEquals(b,authorityValue(db))}finally{db.close()} }
    @Test fun p18Hotfix18_changeSetValidationFailureCausesZeroAuthoritativeMutation() { val db=authorityDb(); try{val b=authorityValue(db); failsChangeSet("DUPLICATE_CHANGE_UID"){engine(DuplicateDraftTrainComponent()).resolve(train(),context())}; assertEquals(b,authorityValue(db))}finally{db.close()} }
    @Test fun p18Hotfix19_singleHandlerRoutingRegression() { val p=resolved(engine(StatComponent(5),FinanceComponent()).resolve(train(),context())); assertTrue(p.changes.single().payload is StatChange); assertEquals(5L,(p.changes.single().payload as StatChange).delta.units) }
    @Test fun p18Hotfix20_duplicateKindRegistrationFailsClosed() { failsEngine("DUPLICATE_COMMAND_RESOLUTION_COMPONENT"){PlayerResolutionComponentRegistry.of(listOf(StatComponent(1),StatComponent(2)))} }
    @Test fun p18Hotfix21_unsupportedCommandFailsClosed() { failsEngine("UNKNOWN_COMMAND_RESOLUTION_COMPONENT"){PlayerDomainEngine(PlayerResolutionComponentRegistry.empty()).resolve(train(),context())} }
    @Test fun p18Hotfix22_projectFailureWithZeroProgressIsPreserved() { val p=resolved(engine(ProjectComponent("FAILURE")).resolve(projectWork(),context())).changes.single().payload as DevelopmentProjectChange; assertEquals(0L,p.progressDelta.units); assertEquals("FAILURE",p.workResultKindUid) }
    @Test fun p18Hotfix23_exactLongDeltaZeroStillRejected() { failsChangeSet("ZERO_DELTA"){ExactLongDelta.of(0)}; assertEquals(Long.MIN_VALUE,ExactLongDelta.of(Long.MIN_VALUE).units); assertEquals(Long.MAX_VALUE,ExactLongDelta.of(Long.MAX_VALUE).units) }
    @Test fun p18Hotfix24_compositeConflictIdentityIsPreserved() { val p=resolved(engine(CompositeStatComponent()).resolve(train(),compositeContext())); assertEquals(2,p.changes.size); PlayerChangeSetValidator.validate(p) }
    @Test fun p18Hotfix25_assetIdentityIsPreserved() { val a=(resolved(engine(AssetComponent()).resolve(assetCommand(),context())).changes.single().payload as AssetChange).asset; assertEquals("RPGOS-ASSET-KIND:PROPERTY:BUSINESS",a.assetKindUid); assertEquals("BUSINESS:A-1",a.assetUid) }
    @Test fun p18Hotfix26_financialLedgerTermsArePreserved() { val p=resolved(engine(FinanceComponent()).resolve(financeCommand(),context())); val c=p.changes.single().payload as FinancialChange; val l=p.ledgerIntents.single().payload as FinancialTransferLedgerIntentPayload; assertEquals(c.fromAccountUid,l.fromAccountUid); assertEquals(c.toAccountUid,l.toAccountUid); assertEquals(c.amountMinor,l.amountMinor); assertEquals(c.currencyUid,l.currencyUid); assertEquals(c.transactionTypeUid,l.transactionTypeUid) }
    @Test fun p18Hotfix27_canonicalSerializationClosure() { val p=resolved(engine(ProjectComponent("NO_PROGRESS")).resolve(projectWork(),context())); val x=PlayerChangeSetCodec.encode(p); val d=PlayerChangeSetCodec.decode(x); assertEquals(p,d); assertEquals(x,PlayerChangeSetCodec.encode(d)) }
    @Test fun p18Hotfix28_fingerprintDeterminism() { val e=engine(StatComponent(3)); val a=resolved(e.resolve(train(),context())); val b=resolved(e.resolve(train(),context())); assertEquals(PlayerChangeSetCodec.fingerprint(a),PlayerChangeSetCodec.fingerprint(b)) }
    @Test fun p18Hotfix29_phase17RepresentativeRegressionLock() { assertEquals(commandRegistry.encode(train()),commandRegistry.encode(commandRegistry.decode(commandRegistry.encode(train())))); assertEquals(OWNERSHIP_SHARE_SCALE,OwnershipShare.full().units); assertEquals(0L,ProjectProgressDelta.of(0).units); try{ProjectProgressDelta.of(-1);fail("negative project progress must fail")}catch(_:PlayerChangeSetStructuralException){}; try{OwnershipShare.full().copy(units=0);fail("ownership invariant must fail")}catch(_:IllegalArgumentException){} }
    @Test fun p18Hotfix30_realIndependentAuthorityFixtureNeverChangesAcrossResolution() { val db=authorityDb(); try{val b=authorityValue(db); resolved(engine(StatComponent(2)).resolve(train(),context())); resolved(engine(ProjectComponent("FAILURE")).resolve(projectWork(),context())); assertTrue(engine(RejectingTrainComponent()).resolve(train(),context()) is PlayerResolutionOutcome.Rejected); assertEquals(b,authorityValue(db))}finally{db.close()} }

    @Test fun componentPayloadTypeMismatchFailsBeforeExecution(){failsEngine("COMMAND_RESOLUTION_COMPONENT_PAYLOAD_TYPE_MISMATCH"){engine(WrongPayloadComponent()).resolve(train(),context())}}
    @Test fun registryInputListAndKindSetAreDefensivelyImmutable(){val list=mutableListOf<PlayerResolutionComponent<out PlayerCommandPayload>>(StatComponent(1));val r=PlayerResolutionComponentRegistry.of(list);list.clear();assertTrue(PlayerCommandKinds.TRAIN in r.commandKindUids);try{@Suppress("UNCHECKED_CAST")(r.commandKindUids as MutableSet<String>).clear();fail("kind set must be immutable")}catch(_:UnsupportedOperationException){}}
    @Test fun exactCommandPayloadDrivesDraftWithoutLossyConversion(){assertEquals(10L,(resolved(engine(EffortTrainComponent()).resolve(train(),context())).changes.single().payload as StatChange).delta.units)}
    @Test fun semanticallyRelevantInputCanProduceDifferentProposal(){val e=engine(EffortTrainComponent());val a=resolved(e.resolve(train(),context()));val b=resolved(e.resolve(train().copy(payload=TrainCommandPayload(DomainRef("STAT","STR"),11,"METHOD")),context()));assertNotEquals(a,b);assertEquals(10L,(a.changes.single().payload as StatChange).delta.units);assertEquals(11L,(b.changes.single().payload as StatChange).delta.units)}
    @Test fun contextCampaignAndActorMismatchAreTypedRejections(){val a=engine(StatComponent(1)).resolve(train(),context(campaignUid="OTHER")) as PlayerResolutionOutcome.Rejected;assertEquals(PlayerResolutionRejectionReason.CONTEXT_CAMPAIGN_MISMATCH,a.rejection.reason);val c=PlayerResolutionContext.create("C1",CommandActorRef("PLAYER","P2"),baseRefs());val b=engine(StatComponent(1)).resolve(train(),c) as PlayerResolutionOutcome.Rejected;assertEquals(PlayerResolutionRejectionReason.CONTEXT_ACTOR_MISMATCH,b.rejection.reason)}
    @Test fun unknownDraftTargetIsRejectedBeforePlayerChangeSetLeavesEngine(){val r=engine(GhostOutputTrainComponent()).resolve(train(),context()) as PlayerResolutionOutcome.Rejected;assertEquals(PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,r.rejection.reason)}
    @Test fun engineOwnsCommandProposalLinkageAndProvenance(){val p=resolved(engine(StatComponent(1)).resolve(train(),context()));assertEquals("C1",p.campaignUid);assertEquals("CMD-TRAIN",p.sourceCommandUid);assertEquals(actor,p.actor);assertEquals("CAUSE",p.causationUid);assertEquals("CORR",p.correlationUid);assertEquals(17L,p.requestedEffectiveOrder);assertEquals("RPGOS-COMPONENT:STAT",p.provenance.resolverKindUid);assertEquals("1",p.provenance.resolverVersion);assertTrue(p.preconditions.contains(ChangeSetExpectedRecordVersion(DomainRef("PLAYER","P1"),3)))}
    @Test fun projectEvidenceListsRemainImmutableAcrossDraftAndProposal(){val x=mutableListOf(DomainRef("EVIDENCE","E1"));val p=resolved(engine(ProjectComponent("FAILURE")).resolve(projectWork(x),context()));x.clear();assertEquals(listOf(DomainRef("EVIDENCE","E1")),(p.changes.single().payload as DevelopmentProjectChange).evidenceRefs)}

    private fun train()=PlayerCommand(commandUid="CMD-TRAIN",campaignUid="C1",actor=actor,commandKindUid=PlayerCommandKinds.TRAIN,payload=TrainCommandPayload(DomainRef("STAT","STR"),10,"METHOD"),provenance=CommandProvenance("TEST"),causationUid="CAUSE",correlationUid="CORR",requestedEffectiveOrder=17,preconditions=listOf(ExpectedRecordVersion(DomainRef("PLAYER","P1"),3)))
    private fun financeCommand()=PlayerCommand(commandUid="CMD-FIN",campaignUid="C1",actor=actor,commandKindUid=PlayerCommandKinds.TRANSFER_FUNDS,payload=TransferFundsCommandPayload("ACCOUNT:A","ACCOUNT:B",125,"CUR:PLN"),provenance=CommandProvenance("TEST"),causationUid="CAUSE-F",correlationUid="CORR-F",requestedEffectiveOrder=18)
    private fun assetCommand()=PlayerCommand(commandUid="CMD-ASSET",campaignUid="C1",actor=actor,commandKindUid=PlayerCommandKinds.ACQUIRE_ASSET,payload=AcquireAssetCommandPayload("RPGOS-ASSET-KIND:PROPERTY:BUSINESS"),provenance=CommandProvenance("TEST"))
    private fun projectWork(e:List<DomainRef> = listOf(DomainRef("EVIDENCE","E1")))=PlayerCommand(commandUid="CMD-PROJECT",campaignUid="C1",actor=actor,commandKindUid=PlayerCommandKinds.RECORD_PROJECT_WORK,payload=RecordProjectWorkCommandPayload("PROJECT:P1","EXPERIMENT",10,"METHOD",e),provenance=CommandProvenance("TEST"),causationUid="CAUSE-P",correlationUid="CORR-P",requestedEffectiveOrder=19)
    private fun context(campaignUid:String="C1",extraRefs:Set<CampaignScopedDomainRef> = emptySet(),entropy:ResolutionEntropyEvidence=ResolutionEntropyEvidence.none())=PlayerResolutionContext.create(campaignUid,actor,baseRefs()+extraRefs,mapOf("RPGOS-DEPENDENCY:REFERENCE-SNAPSHOT" to "1"),entropy)
    private fun compositeContext()=context(extraRefs=setOf(scoped("C1","PLAYER","X:Y"),scoped("C1","STAT","Z"),scoped("C1","PLAYER","X"),scoped("C1","STAT","Y:Z")))
    private fun baseRefs():Set<CampaignScopedDomainRef> = setOf(scoped("C1","PLAYER","P1"),scoped("C1","STAT","STR"),scoped("C1","STAT","STAT:STR"),scoped("C1","PROJECT","PROJECT:P1"),scoped("C1","EVIDENCE","E1"),scoped("C1",PlayerResolutionReferenceKinds.FINANCIAL_ACCOUNT,"ACCOUNT:A"),scoped("C1",PlayerResolutionReferenceKinds.FINANCIAL_ACCOUNT,"ACCOUNT:B"),scoped("C1",PlayerResolutionReferenceKinds.CURRENCY,"CUR:PLN"))
    private fun scoped(c:String,k:String,u:String)=CampaignScopedDomainRef(c,DomainRef(k,u))
    private fun engine(vararg c:PlayerResolutionComponent<out PlayerCommandPayload>)=PlayerDomainEngine(PlayerResolutionComponentRegistry.of(c.toList()))
    private fun resolved(o:PlayerResolutionOutcome)=when(o){is PlayerResolutionOutcome.Resolved->o.proposal;is PlayerResolutionOutcome.Rejected->throw AssertionError("unexpected rejection ${o.rejection.reason}")}
    private fun authorityDb():SQLiteDatabase=SQLiteDatabase.create(null).also{it.execSQL("CREATE TABLE authority_fixture(uid TEXT PRIMARY KEY, value INTEGER NOT NULL)");it.execSQL("INSERT INTO authority_fixture(uid,value) VALUES('A',7)")}
    private fun authorityValue(db:SQLiteDatabase):Long=db.rawQuery("SELECT value FROM authority_fixture WHERE uid='A'",null).use{assertTrue(it.moveToFirst());it.getLong(0)}
    private fun failsEngine(code:String,b:()->Unit){try{b();fail("expected PlayerDomainEngineStructuralException($code)")}catch(e:PlayerDomainEngineStructuralException){assertEquals(code,e.code)}}
    private fun failsChangeSet(code:String,b:()->Unit){try{b();fail("expected PlayerChangeSetStructuralException($code)")}catch(e:PlayerChangeSetStructuralException){assertEquals(code,e.code)}}

    private class StatComponent(private val delta:Long):PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:STAT","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext)=resolvedDraft(statChange("CH-STAT","P1","STAT:STR",delta))}
    private class EffortTrainComponent:PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:EFFORT","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext)=resolvedDraft(statChange("CH-EFFORT","P1","STAT:STR",command.payload.effortUnits))}
    private class EntropyTrainComponent:PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:ENTROPY","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext)=resolvedDraft(statChange("CH-ENTROPY","P1","STAT:STR",context.entropy.exactValue))}
    private class RejectingTrainComponent:PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:REJECT","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext)=PlayerResolutionComponentOutcome.Rejected(PlayerResolutionRejection.create(PlayerResolutionRejectionReason.DOMAIN_REJECTED,detailUid="RPGOS-TEST:EXPECTED_REJECTION"))}
    private class ThrowingTrainComponent:PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:THROW","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext):PlayerResolutionComponentOutcome=throw IllegalStateException("test fault")}
    private class MutableTrainComponent(var delta:Long):PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:MUTABLE","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext)=resolvedDraft(statChange("CH-MUT","P1","STAT:STR",delta))}
    private class DbCapturingTrainComponent(private val authority:SQLiteDatabase):PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:DB","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext):PlayerResolutionComponentOutcome{authority.execSQL("UPDATE authority_fixture SET value=99 WHERE uid='A'");throw IllegalStateException("must never execute")}}
    private class DuplicateDraftTrainComponent:PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:DUP","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext):PlayerResolutionComponentOutcome{val c=statChange("CH-DUP","P1","STAT:STR",1);return PlayerResolutionComponentOutcome.Resolved(PlayerResolutionDraft.create(changes=listOf(c,c)))}}
    private class GhostOutputTrainComponent:PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:GHOST","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext)=resolvedDraft(statChange("CH-GHOST","GHOST-NOT-IN-CAMPAIGN","STAT:STR",1))}
    private class CompositeStatComponent:PlayerResolutionComponent<TrainCommandPayload>(PlayerCommandKinds.TRAIN,TrainCommandPayload::class,"RPGOS-COMPONENT:COMPOSITE","1"){override fun resolve(command:PlayerCommand<TrainCommandPayload>,context:PlayerResolutionContext)=PlayerResolutionComponentOutcome.Resolved(PlayerResolutionDraft.create(changes=listOf(statChange("CH-A","X:Y","Z",1),statChange("CH-B","X","Y:Z",1))))}
    private class ProjectComponent(private val resultKindUid:String):PlayerResolutionComponent<RecordProjectWorkCommandPayload>(PlayerCommandKinds.RECORD_PROJECT_WORK,RecordProjectWorkCommandPayload::class,"RPGOS-COMPONENT:PROJECT","1"){override fun resolve(command:PlayerCommand<RecordProjectWorkCommandPayload>,context:PlayerResolutionContext):PlayerResolutionComponentOutcome{val p=DevelopmentProjectChange.create(command.payload.projectUid,resultKindUid,ProjectProgressDelta.of(0),command.payload.evidenceRefs);return resolvedDraft(PlayerDomainChange.create("CH-PROJECT",PlayerChangeKinds.DEVELOPMENT_PROJECT,p))}}
    private class FinanceComponent:PlayerResolutionComponent<TransferFundsCommandPayload>(PlayerCommandKinds.TRANSFER_FUNDS,TransferFundsCommandPayload::class,"RPGOS-COMPONENT:FINANCE","1"){override fun resolve(command:PlayerCommand<TransferFundsCommandPayload>,context:PlayerResolutionContext):PlayerResolutionComponentOutcome{val p=command.payload;val c=PlayerDomainChange.create("CH-FIN",PlayerChangeKinds.FINANCIAL,FinancialChange(p.fromAccountUid,p.toAccountUid,p.amountMinor,p.currencyUid,"TRANSFER"));val l=PlayerLedgerIntent.create("LED-FIN",PlayerLedgerIntentKinds.FINANCIAL_TRANSFER,listOf(c.changeUid),FinancialTransferLedgerIntentPayload(p.fromAccountUid,p.toAccountUid,p.amountMinor,p.currencyUid,"TRANSFER"));return PlayerResolutionComponentOutcome.Resolved(PlayerResolutionDraft.create(changes=listOf(c),ledgerIntents=listOf(l)))}}
    private class AssetComponent:PlayerResolutionComponent<AcquireAssetCommandPayload>(PlayerCommandKinds.ACQUIRE_ASSET,AcquireAssetCommandPayload::class,"RPGOS-COMPONENT:ASSET","1"){override fun resolve(command:PlayerCommand<AcquireAssetCommandPayload>,context:PlayerResolutionContext)=resolvedDraft(PlayerDomainChange.create("CH-ASSET",PlayerChangeKinds.ASSET,AssetChange(OwnedAssetRef(command.payload.assetKindUid,"BUSINESS:A-1"),"PROPOSED")))}
    private class WrongPayloadComponent:PlayerResolutionComponent<LearnSkillCommandPayload>(PlayerCommandKinds.TRAIN,LearnSkillCommandPayload::class,"RPGOS-COMPONENT:WRONG","1"){override fun resolve(command:PlayerCommand<LearnSkillCommandPayload>,context:PlayerResolutionContext):PlayerResolutionComponentOutcome=throw AssertionError("payload mismatch component must not execute")}
    companion object{private fun statChange(uid:String,subjectUid:String,statUid:String,delta:Long)=PlayerDomainChange.create(uid,PlayerChangeKinds.STAT,StatChange(DomainRef("PLAYER",subjectUid),statUid,ExactLongDelta.of(delta)));private fun resolvedDraft(change:PlayerDomainChange):PlayerResolutionComponentOutcome=PlayerResolutionComponentOutcome.Resolved(PlayerResolutionDraft.create(changes=listOf(change)))}
}
