package com.rpgos.app

import org.junit.Assert.*
import org.junit.Test

class PlayerDomainEngineReferenceClassificationTest {
    private val actor=CommandActorRef("PLAYER","P1")
    @Test fun p18Class01_worldPackSlotIsNotCampaignReference(){assertFalse(DomainRef("EQUIPMENT_SLOT","SLOT:HAND") in draftReferences(equipmentDraft("SLOT:HAND")))}
    @Test fun p18Class02_missingSlotCampaignRefDoesNotReject(){assertResolved(equipmentEngine("SLOT:HAND").resolve(equip("SLOT:HAND"),ctx(DomainRef("ITEM_INSTANCE","ITEM:1"))))}
    @Test fun p18Class03_slotKnownOnlyElsewhereDoesNotBecomeWrongCampaign(){val refs=setOf(CampaignScopedDomainRef("C1",DomainRef("PLAYER","P1")),CampaignScopedDomainRef("C1",DomainRef("ITEM_INSTANCE","ITEM:1")),CampaignScopedDomainRef("C2",DomainRef("EQUIPMENT_SLOT","SLOT:HAND")));assertResolved(equipmentEngine("SLOT:HAND").resolve(equip("SLOT:HAND"),PlayerResolutionContext.createUnboundGeneric("C1",actor,refs)))}
    @Test fun p18Class04_slotSurvivesProposalUnchanged(){val o=equipmentEngine("SLOT:HAND").resolve(equip("SLOT:HAND"),ctx(DomainRef("ITEM_INSTANCE","ITEM:1"))) as PlayerResolutionOutcome.Resolved;assertEquals("SLOT:HAND",(o.proposal.changes.single().payload as EquipmentChange).slotUid)}
    @Test fun p18Class05_phase18DoesNotImplementSlotCompatibilityRules(){assertResolved(equipmentEngine("SLOT:NOT-CHECKED-BY-P18").resolve(equip("SLOT:NOT-CHECKED-BY-P18"),ctx(DomainRef("ITEM_INSTANCE","ITEM:1"))))}
    @Test fun p18Class06_commandAndDraftSlotClassificationAgree(){assertFalse(DomainRef("EQUIPMENT_SLOT","SLOT:HAND") in commandReferences(equip("SLOT:HAND")));assertFalse(DomainRef("EQUIPMENT_SLOT","SLOT:HAND") in draftReferences(equipmentDraft("SLOT:HAND")))}
    @Test fun p18Class07_newOwnershipRecordUidDoesNotNeedKnownReference(){val o=ownershipOutcome("ASSET:1",baseRefs()) as PlayerResolutionOutcome.Resolved;val c=o.proposal.changes.single().payload as OwnershipChange;assertEquals("OWNERSHIP:NEW",c.ownershipRecordUid);assertFalse(baseRefs().any{it.ref.uid==c.ownershipRecordUid})}
    @Test fun p18Class10_existingFullOwnedAssetAccepts(){assertResolved(ownershipOutcome("ASSET:1",baseRefs()))}
    @Test fun p18Class11_unknownAssetRejects(){val r=baseRefs().filterNot{it.ref==DomainRef("ASSET_KIND:A","ASSET:1")}.toSet();assertRejected(ownershipOutcome("ASSET:1",r),PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,DomainRef("ASSET_KIND:A","ASSET:1"))}
    @Test fun p18Class12_sameAssetUidWrongKindDoesNotSatisfyLookup(){val r=baseRefs().filterNot{it.ref==DomainRef("ASSET_KIND:A","ASSET:1")}.toMutableSet();r+=CampaignScopedDomainRef("C1",DomainRef("ASSET_KIND:B","ASSET:1"));assertRejected(ownershipOutcome("ASSET:1",r),PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,DomainRef("ASSET_KIND:A","ASSET:1"))}
    @Test fun p18Class13_wrongCampaignAssetRejects(){val r=baseRefs().filterNot{it.ref==DomainRef("ASSET_KIND:A","ASSET:1")}.toMutableSet();r+=CampaignScopedDomainRef("C2",DomainRef("ASSET_KIND:A","ASSET:1"));assertRejected(ownershipOutcome("ASSET:1",r),PlayerResolutionRejectionReason.WRONG_CAMPAIGN_REFERENCE,DomainRef("ASSET_KIND:A","ASSET:1"))}
    @Test fun p18Class14_existingFromOwnerAccepts(){assertResolved(ownershipOutcome("ASSET:1",baseRefs()))}
    @Test fun p18Class15_unknownFromOwnerRejects(){val r=baseRefs().filterNot{it.ref==DomainRef("OWNER_KIND:PARTY","OWNER:FROM")}.toSet();assertRejected(ownershipOutcome("ASSET:1",r),PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,DomainRef("OWNER_KIND:PARTY","OWNER:FROM"))}
    @Test fun p18Class15b_wrongCampaignFromOwnerRejects(){val r=baseRefs().filterNot{it.ref==DomainRef("OWNER_KIND:PARTY","OWNER:FROM")}.toMutableSet();r+=CampaignScopedDomainRef("C2",DomainRef("OWNER_KIND:PARTY","OWNER:FROM"));assertRejected(ownershipOutcome("ASSET:1",r),PlayerResolutionRejectionReason.WRONG_CAMPAIGN_REFERENCE,DomainRef("OWNER_KIND:PARTY","OWNER:FROM"))}
    @Test fun p18Class16_existingToOwnerAccepts(){assertResolved(ownershipOutcome("ASSET:1",baseRefs()))}
    @Test fun p18Class17_unknownToOwnerRejects(){val r=baseRefs().filterNot{it.ref==DomainRef("OWNER_KIND:PARTY","OWNER:TO")}.toSet();assertRejected(ownershipOutcome("ASSET:1",r),PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,DomainRef("OWNER_KIND:PARTY","OWNER:TO"))}
    @Test fun p18Class17b_wrongCampaignToOwnerRejects(){val r=baseRefs().filterNot{it.ref==DomainRef("OWNER_KIND:PARTY","OWNER:TO")}.toMutableSet();r+=CampaignScopedDomainRef("C2",DomainRef("OWNER_KIND:PARTY","OWNER:TO"));assertRejected(ownershipOutcome("ASSET:1",r),PlayerResolutionRejectionReason.WRONG_CAMPAIGN_REFERENCE,DomainRef("OWNER_KIND:PARTY","OWNER:TO"))}
    @Test fun p18Class18_componentCannotSubstituteGhostOwnershipIdentity(){val c=transfer(DomainRef("ASSET_KIND:A","ASSET:CMD"),DomainRef("OWNER_KIND:PARTY","OWNER:CMD-TO"));val r=setOf(CampaignScopedDomainRef("C1",DomainRef("ASSET_KIND:A","ASSET:CMD")),CampaignScopedDomainRef("C1",DomainRef("OWNER_KIND:PARTY","OWNER:CMD-TO")),CampaignScopedDomainRef("C1",DomainRef("OWNER_KIND:PARTY","OWNER:FROM")),CampaignScopedDomainRef("C1",DomainRef("OWNER_KIND:PARTY","OWNER:TO")));assertRejected(ownershipEngine("ASSET:GHOST").resolve(c,PlayerResolutionContext.createUnboundGeneric("C1",actor,r)),PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,DomainRef("ASSET_KIND:A","ASSET:GHOST"))}
    @Test fun p18Class18b_componentCannotSubstituteGhostOwner(){val c=transfer(DomainRef("ASSET_KIND:A","ASSET:1"),DomainRef("OWNER_KIND:PARTY","OWNER:CMD-TO"));val r=baseRefs().toMutableSet();r+=CampaignScopedDomainRef("C1",DomainRef("OWNER_KIND:PARTY","OWNER:CMD-TO"));assertRejected(ownershipEngine("ASSET:1",toOwnerUid="OWNER:GHOST").resolve(c,PlayerResolutionContext.createUnboundGeneric("C1",actor,r)),PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,DomainRef("OWNER_KIND:PARTY","OWNER:GHOST"))}
    @Test fun p18Class19_commandValidIdentityDoesNotBlessUnrelatedDraftIdentity(){val c=transfer(DomainRef("ASSET_KIND:A","ASSET:COMMAND"),DomainRef("OWNER_KIND:PARTY","OWNER:TO"));val r=baseRefs().toMutableSet();r+=CampaignScopedDomainRef("C1",DomainRef("ASSET_KIND:A","ASSET:COMMAND"));assertRejected(ownershipEngine("ASSET:DRAFT-ONLY").resolve(c,PlayerResolutionContext.createUnboundGeneric("C1",actor,r)),PlayerResolutionRejectionReason.UNKNOWN_REFERENCE,DomainRef("ASSET_KIND:A","ASSET:DRAFT-ONLY"))}
    @Test fun p18Class20_fullOwnershipNamespaceSurvivesProposal(){val e=change("ASSET:1");val a=((ownershipOutcome("ASSET:1",baseRefs()) as PlayerResolutionOutcome.Resolved).proposal.changes.single().payload as OwnershipChange);assertEquals(e.asset,a.asset);assertEquals(e.fromOwner,a.fromOwner);assertEquals(e.toOwner,a.toOwner);assertEquals(e.ownershipRecordUid,a.ownershipRecordUid)}

    private fun equipmentDraft(s:String)=PlayerResolutionDraft.create(changes=listOf(PlayerDomainChange.create("CHANGE:EQUIP",PlayerChangeKinds.EQUIPMENT,EquipmentChange(DomainRef("PLAYER","P1"),s,EquipmentOperation.EQUIP,"ITEM:1"))))
    private fun equip(s:String)=PlayerCommand(commandUid="CMD:EQUIP",campaignUid="C1",actor=actor,commandKindUid=PlayerCommandKinds.EQUIP_ITEM,payload=EquipItemCommandPayload(DomainRef("ITEM_INSTANCE","ITEM:1"),s),provenance=CommandProvenance("TEST"))
    private fun equipmentEngine(s:String)=PlayerDomainEngine(PlayerResolutionComponentRegistry.of(listOf(EquipmentComponent(s))))
    private fun change(a:String)=OwnershipChange("OWNERSHIP:NEW",OwnedAssetRef("ASSET_KIND:A",a),OwnershipOwnerRef("OWNER_KIND:PARTY","OWNER:FROM"),OwnershipOwnerRef("OWNER_KIND:PARTY","OWNER:TO"),OwnershipShare.full())
    private fun transfer(s:DomainRef=DomainRef("ASSET_KIND:A","ASSET:1"),t:DomainRef=DomainRef("OWNER_KIND:PARTY","OWNER:TO"))=PlayerCommand(commandUid="CMD:OWNERSHIP",campaignUid="C1",actor=actor,commandKindUid=PlayerCommandKinds.TRANSFER_OWNERSHIP,payload=TransferOwnershipCommandPayload(s,t,10_000L),provenance=CommandProvenance("TEST"))
    private fun ownershipEngine(a:String,fromOwnerUid:String="OWNER:FROM",toOwnerUid:String="OWNER:TO")=PlayerDomainEngine(PlayerResolutionComponentRegistry.of(listOf(OwnershipComponent(a,fromOwnerUid,toOwnerUid))))
    private fun ownershipOutcome(a:String,r:Set<CampaignScopedDomainRef>)=ownershipEngine(a).resolve(transfer(),PlayerResolutionContext.createUnboundGeneric("C1",actor,r))
    private fun baseRefs()=setOf(CampaignScopedDomainRef("C1",DomainRef("ASSET_KIND:A","ASSET:1")),CampaignScopedDomainRef("C1",DomainRef("OWNER_KIND:PARTY","OWNER:FROM")),CampaignScopedDomainRef("C1",DomainRef("OWNER_KIND:PARTY","OWNER:TO")))
    private fun ctx(vararg r:DomainRef)=PlayerResolutionContext.createUnboundGeneric("C1",actor,(listOf(DomainRef("PLAYER","P1"))+r).map{CampaignScopedDomainRef("C1",it)}.toSet())
    private fun assertResolved(o:PlayerResolutionOutcome)=assertTrue(o is PlayerResolutionOutcome.Resolved)
    private fun assertRejected(o:PlayerResolutionOutcome,reason:PlayerResolutionRejectionReason,ref:DomainRef){assertTrue(o is PlayerResolutionOutcome.Rejected);val x=(o as PlayerResolutionOutcome.Rejected).rejection;assertEquals(reason,x.reason);assertEquals(listOf(ref),x.relatedRefs)}

    private class EquipmentComponent(private val slot:String):PlayerResolutionComponent<EquipItemCommandPayload>(PlayerCommandKinds.EQUIP_ITEM,EquipItemCommandPayload::class,"COMP:EQUIP-CLASS","1"){
        override fun resolve(command:PlayerCommand<EquipItemCommandPayload>,context:PlayerResolutionContext)=PlayerResolutionComponentOutcome.Resolved(PlayerResolutionDraft.create(changes=listOf(PlayerDomainChange.create("CHANGE:EQUIP",PlayerChangeKinds.EQUIPMENT,EquipmentChange(DomainRef("PLAYER","P1"),slot,EquipmentOperation.EQUIP,"ITEM:1")))))
    }
    private class OwnershipComponent(private val assetUid:String,private val fromOwnerUid:String,private val toOwnerUid:String):PlayerResolutionComponent<TransferOwnershipCommandPayload>(PlayerCommandKinds.TRANSFER_OWNERSHIP,TransferOwnershipCommandPayload::class,"COMP:OWNERSHIP-CLASS","1"){
        override fun resolve(command:PlayerCommand<TransferOwnershipCommandPayload>,context:PlayerResolutionContext)=PlayerResolutionComponentOutcome.Resolved(PlayerResolutionDraft.create(changes=listOf(PlayerDomainChange.create("CHANGE:OWNERSHIP",PlayerChangeKinds.OWNERSHIP,OwnershipChange("OWNERSHIP:NEW",OwnedAssetRef("ASSET_KIND:A",assetUid),OwnershipOwnerRef("OWNER_KIND:PARTY",fromOwnerUid),OwnershipOwnerRef("OWNER_KIND:PARTY",toOwnerUid),OwnershipShare.full())))))
    }
}
