package com.rpgos.app

import android.database.sqlite.SQLiteDatabase
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.File

@RunWith(RobolectricTestRunner::class)
@Config(sdk=[34])
class SkillPersistenceTest {
    private lateinit var dbFile: File
    @Before fun setUp(){dbFile=File.createTempFile("rpgos-phase7-",".db");dbFile.delete()}
    @After fun tearDown(){dbFile.delete()}

    @Test fun typedDefinitionLearnMasteryProgressIsolationAndReopen(){
        open().use{db->seed(db);val s=SkillStore(db,"C");s.registerDefinitions("W",listOf(def("S")));s.savePlayerSkill(PlayerSkill("C","P","S",80.0,12.0,"xp:v1",1,"creation",4));assertEquals(80.0,s.playerSkills("P").single().baseMastery,0.0)}
        open().use{db->MigrationManager().ensureV7(db,"C");val s=SkillStore(db,"C");val p=s.playerSkills("P").single();assertEquals(80.0,p.baseMastery,0.0);assertEquals(12.0,p.progressValue!!,0.0);assertEquals("xp:v1",p.progressSemanticsUid);assertTrue(SkillStore(db,"OTHER").playerSkills("P").isEmpty());assertTrue(s.playerSkills("OTHER_PLAYER").isEmpty())}
    }

    @Test fun ownershipDuplicateUidSameLabelAndDomainBindingAreValidated(){open().use{db->seed(db);val ps=ProgressionProfileStore(db,"C");ps.registerDomains("W",listOf(domain("D","W")));val s=SkillStore(db,"C");s.registerDefinitions("W",listOf(def("A","a",domains=listOf("D")),def("B","b",name="Same Label")));expectFailure{s.registerDefinitions("W",listOf(def("A","x")))};expectFailure{s.registerDefinitions("OTHER",listOf(def("X","x",pack="W")))};s.registerDefinitions("OTHER",listOf(def("C","c",pack="OTHER",name="Same Label")));assertEquals(3,s.definitions().size);expectFailure{s.registerDefinitions("W",listOf(def("Z","z",domains=listOf("MISSING"))))}}}

    @Test fun legacyIsVisibleLosslessUnknownAndExplicitMappingProducesOneLogicalSkill(){open().use{db->legacyTables(db);db.execSQL("INSERT INTO skill_definitions VALUES('legacy-a','Legacy A','generic')");db.execSQL("INSERT INTO character_skills VALUES('P','legacy-a',77.5,123.25,9)");db.execSQL("INSERT INTO character_skills VALUES('P','orphan',5.0,7.0,10)");val before=legacyDump(db);MigrationManager().ensureV7(db,"C");val s=SkillStore(db,"C");var read=s.reconciled("P");assertEquals(0,read.skills.size);assertEquals(2,read.unresolvedLegacy.size);s.registerDefinitions("W",listOf(def("CANON")));s.registerLegacyMapping(LegacySkillMapping("C","P","legacy-a","CANON","W",1,"explicit-pack-map"));read=s.reconciled("P");assertEquals(1,read.skills.size);assertEquals(77.5,read.skills.single().playerSkill.baseMastery,0.0);assertEquals("123.25",read.skills.single().legacyXpRaw);assertEquals(listOf("orphan"),read.unresolvedLegacy.map{it.legacySkillUid});assertEquals(before,legacyDump(db))}}

    @Test fun mixedLegacyTypedSameUidWithoutMappingFailsLoud(){open().use{db->legacyTables(db);db.execSQL("INSERT INTO character_skills VALUES('P','S',40.0,0.0,1)");MigrationManager().ensureV7(db,"C");val s=SkillStore(db,"C");s.registerDefinitions("W",listOf(def("S")));expectFailure{s.savePlayerSkill(PlayerSkill("C","P","S",50.0,provenance="typed"))}}}

    @Test fun modifiersChangeEffectiveMasteryOnlyAndRemovalRestoresBase(){open().use{db->MigrationManager().ensureV7(db,"C");val s=SkillStore(db,"C");s.registerDefinitions("W",listOf(def("S",max=100.0)));val player=PlayerSkill("C","P","S",80.0,provenance="learned");s.savePlayerSkill(player);val ms=ModifierStore(db,"C");ms.save(mod("inj",ModifierLifecycle.INJURY,ModifierOperation.ADD_FLAT,-30.0));ms.save(mod("gear",ModifierLifecycle.EQUIPMENT,ModifierOperation.ADD_FLAT,5.0));ms.save(mod("buff",ModifierLifecycle.TEMPORARY,ModifierOperation.ADD_FLAT,10.0));val request:(List<Modifier>)->DerivedResolutionRequest={mods->DerivedResolutionRequest("C","P",5,emptyList(),emptyList(),emptyList(),emptyList(),mods,skillDefinitions=s.definitions(),playerSkills=s.playerSkills("P"))};val first=DerivedValueResolver().resolve(request(ms.modifiers("P"))).resolvedSkills.single();assertEquals(65.0,first.effectiveMastery,0.0);assertEquals(80.0,s.playerSkills("P").single().baseMastery,0.0);ms.remove("P","inj");ms.remove("P","gear");ms.remove("P","buff");assertEquals(80.0,DerivedValueResolver().resolve(request(ms.modifiers("P"))).resolvedSkills.single().effectiveMastery,0.0);assertEquals(80.0,s.playerSkills("P").single().baseMastery,0.0)}}

    @Test fun skillModifierOrderingIsDeterministicAndScopesCannotLeak(){open().use{db->MigrationManager().ensureV7(db,"C");val s=SkillStore(db,"C");s.registerDefinitions("W",listOf(def("S")));val p=PlayerSkill("C","P","S",50.0,provenance="x");s.savePlayerSkill(p);val mods=listOf(mod("b",ModifierLifecycle.TEMPORARY,ModifierOperation.ADD_FLAT,2.0,priority=1),mod("a",ModifierLifecycle.TEMPORARY,ModifierOperation.ADD_FLAT,1.0,priority=1));val r1=DerivedValueResolver().resolve(DerivedResolutionRequest("C","P",0,emptyList(),emptyList(),emptyList(),emptyList(),mods,skillDefinitions=s.definitions(),playerSkills=listOf(p)));val r2=DerivedValueResolver().resolve(DerivedResolutionRequest("C","P",0,emptyList(),emptyList(),emptyList(),emptyList(),mods.reversed(),skillDefinitions=s.definitions(),playerSkills=listOf(p)));assertEquals(r1.inputFingerprint,r2.inputFingerprint);assertEquals(listOf("a","b"),r1.resolvedSkills.single().contributions.map{it.modifierUid});expectFailure{DerivedValueResolver().resolve(DerivedResolutionRequest("C","P",0,emptyList(),emptyList(),emptyList(),emptyList(),listOf(mod("leak",ModifierLifecycle.INJURY,ModifierOperation.ADD_FLAT,-1.0).copy(characterUid="Q")),skillDefinitions=s.definitions(),playerSkills=listOf(p)))}}}

    @Test fun talentPotentialStatAndTechniqueAreNotMutatedBySkillWrites(){open().use{db->db.execSQL("CREATE TABLE character_techniques(entity_uid TEXT,technique_uid TEXT,mastery REAL)");db.execSQL("INSERT INTO character_techniques VALUES('P','T',33.0)");MigrationManager().ensureV7(db,"C");val profiles=ProgressionProfileStore(db,"C");profiles.registerDomains("W",listOf(domain("D","W")));profiles.saveTalent(TalentEntry("C","P","D",0.9,provenance="t"));profiles.savePotential(PotentialEntry("C","P","D","growth",0.2,provenance="p"));val sr=StatResourceStore(db,"C");sr.registerStatDefinitions("W",listOf(StatDefinition("ST","stat","generic",worldPackUid="W")));sr.savePlayerStat(PlayerStat("C","P","ST",100.0));val s=SkillStore(db,"C");s.registerDefinitions("W",listOf(def("S",domains=listOf("D"))));s.savePlayerSkill(PlayerSkill("C","P","S",80.0,provenance="learned"));profiles.saveTalent(TalentEntry("C","P","D",0.1,2,"t2"));profiles.savePotential(PotentialEntry("C","P","D","growth",0.8,2,"p2"));assertEquals(80.0,s.playerSkills("P").single().baseMastery,0.0);assertEquals(100.0,scalarDouble(db,"SELECT base_value FROM player_stats WHERE stat_uid='ST'"),0.0);assertEquals(33.0,scalarDouble(db,"SELECT mastery FROM character_techniques WHERE technique_uid='T'"),0.0)}}

    @Test fun invalidMasteryNaNInfinityAndDeclaredRangeFail(){open().use{db->MigrationManager().ensureV7(db,"C");val s=SkillStore(db,"C");s.registerDefinitions("W",listOf(def("S",max=100.0),def("UNBOUND","unbound",max=null)));expectFailure{s.savePlayerSkill(PlayerSkill("C","P","S",-1.0,provenance="x"))};expectFailure{s.savePlayerSkill(PlayerSkill("C","P","S",Double.NaN,provenance="x"))};expectFailure{s.savePlayerSkill(PlayerSkill("C","P","S",Double.POSITIVE_INFINITY,provenance="x"))};expectFailure{s.savePlayerSkill(PlayerSkill("C","P","S",101.0,provenance="x"))};s.savePlayerSkill(PlayerSkill("C","P","UNBOUND",1.0e200,provenance="x"));assertEquals(1.0e200,s.playerSkills("P").single{it.skillUid=="UNBOUND"}.baseMastery,0.0)}}

    @Test fun migrationIsIdempotentPreservesOldStateAndExtendsModifierCheckLosslessly(){open().use{db->MigrationManager().ensureV6(db,"C");val sr=StatResourceStore(db,"C");sr.registerStatDefinitions("W",listOf(StatDefinition("ST","stat","generic",worldPackUid="W")));sr.savePlayerStat(PlayerStat("C","P","ST",10.0));ModifierStore(db,"C").save(Modifier("old","C","P","ST",ModifierTargetKind.STAT_EFFECTIVE,ModifierLifecycle.INJURY,ModifierOperation.ADD_FLAT,-1.0,sourceType="T",sourceUid="S",provenance="old"));MigrationManager().ensureV7(db,"C");MigrationManager().ensureV7(db,"C");assertEquals(1,scalarInt(db,"SELECT COUNT(*) FROM rpgos_schema_migrations WHERE migration_id='$PHASE7_MIGRATION_ID'"));assertEquals(1,scalarInt(db,"SELECT COUNT(*) FROM modifiers WHERE modifier_uid='old'"));assertEquals(10.0,scalarDouble(db,"SELECT base_value FROM player_stats WHERE stat_uid='ST'"),0.0);assertTrue(scalarText(db,"SELECT sql FROM sqlite_master WHERE type='table' AND name='modifiers'").contains("SKILL_EFFECTIVE"))}}

    @Test fun thousandSkillsNoTruncationAndIntegrityChecksClean(){open().use{db->db.execSQL("PRAGMA foreign_keys=ON");MigrationManager().ensureV7(db,"C");val s=SkillStore(db,"C");val defs=(0 until 1005).map{i->def("S%04d".format(i),"k%04d".format(i))};s.registerDefinitions("W",defs);db.beginTransaction();try{defs.forEachIndexed{i,d->s.savePlayerSkill(PlayerSkill("C","P",d.skillUid,i.toDouble(),provenance="bulk"))};db.setTransactionSuccessful()}finally{db.endTransaction()};assertEquals(1005,s.playerSkills("P").size);db.rawQuery("PRAGMA integrity_check",null).use{c->assertTrue(c.moveToFirst());assertEquals("ok",c.getString(0))};db.rawQuery("PRAGMA foreign_key_check",null).use{c->assertFalse(c.moveToFirst())}}}

    @Test fun currentSchemaEntrypointReachesPhase7(){open().use{db->CurrentSchema.ensure(db,"C");assertEquals(1,scalarInt(db,"SELECT COUNT(*) FROM rpgos_schema_migrations WHERE migration_id='$PHASE7_MIGRATION_ID'"));assertEquals(1,scalarInt(db,"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='player_skills_v2'"))}}

    private fun seed(db:SQLiteDatabase){MigrationManager().ensureV7(db,"C")}
    private fun legacyTables(db:SQLiteDatabase){db.execSQL("CREATE TABLE skill_definitions(skill_uid TEXT PRIMARY KEY,name TEXT,category TEXT)");db.execSQL("CREATE TABLE character_skills(entity_uid TEXT,skill_uid TEXT,mastery REAL,xp REAL,updated_chapter INTEGER)")}
    private fun def(uid:String,key:String=uid.lowercase(),pack:String="W",name:String="Skill $uid",domains:List<String> = emptyList(),max:Double?=null)=SkillDefinition(uid,pack,key,name,"generic",domains,0.0,max,SkillDefinitionStatus.ACTIVE,1,"world-pack")
    private fun domain(uid:String,pack:String)=ProgressionDomainDefinition(uid,pack,uid.lowercase(),"Domain","generic",definitionVersion=1,provenance="pack")
    private fun mod(uid:String,life:ModifierLifecycle,op:ModifierOperation,value:Double,priority:Int=0)=Modifier(uid,"C","P","S",ModifierTargetKind.SKILL_EFFECTIVE,life,op,value,priority,sourceType="TEST",sourceUid=uid,provenance="test")
    private fun legacyDump(db:SQLiteDatabase)=db.rawQuery("SELECT entity_uid||'|'||skill_uid||'|'||CAST(mastery AS TEXT)||'|'||CAST(xp AS TEXT)||'|'||CAST(updated_chapter AS TEXT) FROM character_skills ORDER BY skill_uid",null).use{c->buildList{while(c.moveToNext())add(c.getString(0))}}
    private fun open()=SQLiteDatabase.openOrCreateDatabase(dbFile,null)
    private fun scalarDouble(db:SQLiteDatabase,sql:String)=db.rawQuery(sql,null).use{c->require(c.moveToFirst());c.getDouble(0)}
    private fun scalarInt(db:SQLiteDatabase,sql:String)=db.rawQuery(sql,null).use{c->require(c.moveToFirst());c.getInt(0)}
    private fun scalarText(db:SQLiteDatabase,sql:String)=db.rawQuery(sql,null).use{c->require(c.moveToFirst());c.getString(0)}
    private fun expectFailure(block:()->Unit){try{block();fail("Expected failure")}catch(_:IllegalArgumentException){}catch(_:IllegalStateException){}}
}
