package com.rpgos.app

import android.database.sqlite.SQLiteDatabase
import org.junit.After
import org.junit.Assert.*
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config
import java.io.File

@RunWith(RobolectricTestRunner::class)
@Config(sdk=[34])
class TechniquePersistenceTest {
    private lateinit var dbFile:File
    @Before fun setUp(){dbFile=File.createTempFile("rpgos-phase8-",".db");dbFile.delete()}
    @After fun tearDown(){dbFile.delete()}

    @Test fun definitionLearnHistoryProgressIsolationAndReopen(){
        open().use{db->MigrationManager().ensureV8(db,"C");val s=TechniqueStore(db,"C");s.registerDefinitions("W",listOf(def("T")));s.savePlayerTechnique(PlayerTechnique("C","P","T",72.0,14.0,"legacy-xp:v1",3,9,20,13,4,true,"note",1,"learned"));assertEquals(72.0,s.playerTechniques("P").single().baseMastery,0.0)}
        open().use{db->MigrationManager().ensureV8(db,"C");val t=TechniqueStore(db,"C").playerTechniques("P").single();assertEquals(14.0,t.progressValue!!,0.0);assertEquals("legacy-xp:v1",t.progressSemanticsUid);assertEquals(3L,t.learnedChapter);assertEquals(9L,t.lastUsedChapter);assertEquals(20L,t.usageCount);assertEquals(13L,t.successCount);assertEquals(4L,t.failureCount);assertTrue(t.isEquipped);assertEquals("note",t.notes);assertTrue(TechniqueStore(db,"OTHER").playerTechniques("P").isEmpty());assertTrue(TechniqueStore(db,"C").playerTechniques("Q").isEmpty())}
    }

    @Test fun ownershipDuplicatesSameLabelRequirementsAndGenericResourceCosts(){open().use{db->MigrationManager().ensureV8(db,"C");SkillStore(db,"C").registerDefinitions("W",listOf(skill("S")));StatResourceStore(db,"C").registerResourceDefinitions("RES",listOf(ResourceDefinition("R","energy","generic",worldPackUid="RES")));val s=TechniqueStore(db,"C");s.registerDefinitions("W",listOf(def("A",key="a",name="Same",req=listOf(req("S",TechniqueRequirementPhase.ACQUISITION,TechniqueSkillMasteryBasis.BASE,10.0)),cost=listOf(TechniqueResourceCost("R",5.0,provenance="pack")))));expectFailure{s.registerDefinitions("W",listOf(def("A",key="other")))};expectFailure{s.registerDefinitions("OTHER",listOf(def("X",pack="W")))};s.registerDefinitions("OTHER",listOf(def("B",pack="OTHER",name="Same")));assertEquals(2,s.definitions().size);expectFailure{s.registerDefinitions("W",listOf(def("M",req=listOf(req("MISSING",TechniqueRequirementPhase.ACQUISITION,TechniqueSkillMasteryBasis.BASE,1.0)))))};expectFailure{s.registerDefinitions("W",listOf(def("N",cost=listOf(TechniqueResourceCost("MISSING",1.0,provenance="x")))))};assertEquals("R",s.definitions().single{it.techniqueUid=="A"}.resourceCosts.single().resourceUid)}}

    @Test fun legacyVisibleOrphanLosslessHistoryXpAndExplicitMapping(){open().use{db->legacyTables(db);db.execSQL("INSERT INTO technique_definitions VALUES('legacy-a','Legacy A','generic',12.5)");db.execSQL("INSERT INTO character_techniques VALUES('P','legacy-a',67.5,123.25,2,7,11,8,3,1,'legacy note',8.5)");db.execSQL("INSERT INTO character_techniques VALUES('P','orphan',4.0,9.0,1,NULL,0,0,0,0,NULL,NULL)");val before=legacyDump(db);MigrationManager().ensureV8(db,"C");val s=TechniqueStore(db,"C");var read=s.reconciled("P");assertEquals(0,read.techniques.size);assertEquals(2,read.unresolvedLegacy.size);s.registerDefinitions("W",listOf(def("CANON")));s.registerLegacyMapping(LegacyTechniqueMapping("C","P","legacy-a","CANON","W",1,"explicit"));read=s.reconciled("P");val r=read.techniques.single();assertEquals(67.5,r.playerTechnique.baseMastery,0.0);assertEquals("123.25",r.legacyXpRaw);assertEquals("8.5",r.legacyChakraCostOverrideRaw);assertEquals("12.5",r.legacyBaseChakraCostRaw);assertEquals(2L,r.playerTechnique.learnedChapter);assertEquals(7L,r.playerTechnique.lastUsedChapter);assertEquals(11L,r.playerTechnique.usageCount);assertEquals(8L,r.playerTechnique.successCount);assertEquals(3L,r.playerTechnique.failureCount);assertTrue(r.playerTechnique.isEquipped);assertEquals("legacy note",r.playerTechnique.notes);assertEquals(listOf("orphan"),read.unresolvedLegacy.map{it.legacyTechniqueUid});assertEquals(before,legacyDump(db))}}

    @Test fun explicitLegacyResourceMappingMapsIdentityOnlyAndPreservesRawCosts(){open().use{db->legacyTables(db);db.execSQL("INSERT INTO technique_definitions VALUES('legacy-a','Legacy A','generic',20.0)");db.execSQL("INSERT INTO character_techniques VALUES('P','legacy-a',10.0,0.0,1,NULL,0,0,0,0,NULL,7.0)");MigrationManager().ensureV8(db,"C");StatResourceStore(db,"C").registerResourceDefinitions("RES",listOf(ResourceDefinition("ENERGY","energy","generic",worldPackUid="RES")));val s=TechniqueStore(db,"C");s.registerDefinitions("W",listOf(def("CANON")));val unresolved=s.reconciled("P").unresolvedLegacy.single();assertEquals("7.0",unresolved.chakraCostOverrideRaw);assertEquals("20.0",unresolved.baseChakraCostRaw);expectFailure{s.registerLegacyResourceCostMapping(LegacyTechniqueResourceCostMapping("C","P","legacy-a","ENERGY","W",1,"map"))};s.registerLegacyMapping(LegacyTechniqueMapping("C","P","legacy-a","CANON","W",1,"identity"));s.registerLegacyResourceCostMapping(LegacyTechniqueResourceCostMapping("C","P","legacy-a","ENERGY","W",1,"map"));val r=s.reconciled("P").techniques.single();assertEquals("ENERGY",r.mappedLegacyCostResourceUid);assertEquals("7.0",r.legacyChakraCostOverrideRaw);assertEquals("20.0",r.legacyBaseChakraCostRaw)}}

    @Test fun mixedLegacyTypedWithoutMappingFailsLoudAndSupersessionProducesOne(){open().use{db->legacyTables(db);db.execSQL("INSERT INTO character_techniques VALUES('P','T',40.0,0.0,1,NULL,0,0,0,0,NULL,NULL)");MigrationManager().ensureV8(db,"C");val s=TechniqueStore(db,"C");s.registerDefinitions("W",listOf(def("T")));expectFailure{s.savePlayerTechnique(PlayerTechnique("C","P","T",50.0,provenance="typed"))};s.registerDefinitions("W",listOf(def("CANON",key="canon")));s.savePlayerTechnique(PlayerTechnique("C","P","CANON",55.0,provenance="typed"));s.registerLegacyMapping(LegacyTechniqueMapping("C","P","T","CANON","W",1,"explicit",true));val read=s.reconciled("P");assertEquals(1,read.techniques.size);assertEquals(55.0,read.techniques.single().playerTechnique.baseMastery,0.0);assertTrue(read.unresolvedLegacy.isEmpty())}}

    @Test fun skillRequirementsHaveExplicitPhaseAndBaseOrEffectiveViewWithoutMasteryCopy(){open().use{db->MigrationManager().ensureV8(db,"C");val ss=SkillStore(db,"C");ss.registerDefinitions("W",listOf(skill("S")));ss.savePlayerSkill(PlayerSkill("C","P","S",80.0,provenance="skill"));val ts=TechniqueStore(db,"C");ts.registerDefinitions("W",listOf(def("T",req=listOf(req("S",TechniqueRequirementPhase.ACQUISITION,TechniqueSkillMasteryBasis.BASE,70.0),req("S",TechniqueRequirementPhase.EXECUTION,TechniqueSkillMasteryBasis.EFFECTIVE,70.0)))));assertTrue(ts.requirementsSatisfied("P","T",TechniqueRequirementPhase.ACQUISITION,0,emptyList()));assertTrue(ts.requirementsSatisfied("P","T",TechniqueRequirementPhase.EXECUTION,0,emptyList()));val injury=Modifier("inj","C","P","S",ModifierTargetKind.SKILL_EFFECTIVE,ModifierLifecycle.INJURY,ModifierOperation.ADD_FLAT,-20.0,sourceType="TEST",sourceUid="inj",provenance="test");assertTrue(ts.requirementsSatisfied("P","T",TechniqueRequirementPhase.ACQUISITION,0,listOf(injury)));assertFalse(ts.requirementsSatisfied("P","T",TechniqueRequirementPhase.EXECUTION,0,listOf(injury)));ts.savePlayerTechnique(PlayerTechnique("C","P","T",13.0,provenance="learned"));ss.savePlayerSkill(PlayerSkill("C","P","S",99.0,provenance="skill-update"));assertEquals(13.0,ts.playerTechniques("P").single().baseMastery,0.0)}}

    @Test fun techniqueModifiersAreDerivedDeterministicAndNoRetrogression(){open().use{db->MigrationManager().ensureV8(db,"C");val s=TechniqueStore(db,"C");s.registerDefinitions("W",listOf(def("T",max=100.0)));val p=PlayerTechnique("C","P","T",80.0,provenance="learned");s.savePlayerTechnique(p);val mods=listOf(tmod("b",5.0,1),tmod("a",-30.0,1));fun resolve(ms:List<Modifier>)=DerivedValueResolver().resolve(DerivedResolutionRequest("C","P",0,emptyList(),emptyList(),emptyList(),emptyList(),ms,techniqueDefinitions=s.definitions(),playerTechniques=listOf(p))).resolvedTechniques.single();val a=resolve(mods);val b=resolve(mods.reversed());assertEquals(a.effectiveMastery,b.effectiveMastery,0.0);assertEquals(listOf("a","b"),a.contributions.map{it.modifierUid});assertEquals(55.0,a.effectiveMastery,0.0);assertEquals(80.0,s.playerTechniques("P").single().baseMastery,0.0);assertEquals(80.0,resolve(emptyList()).effectiveMastery,0.0);expectFailure{DerivedValueResolver().resolve(DerivedResolutionRequest("C","P",0,emptyList(),emptyList(),emptyList(),emptyList(),listOf(tmod("leak",-1.0).copy(characterUid="Q")),techniqueDefinitions=s.definitions(),playerTechniques=listOf(p)))}}}

    @Test fun talentPotentialAndSkillDoNotRewriteTechniqueMastery(){open().use{db->MigrationManager().ensureV8(db,"C");val profiles=ProgressionProfileStore(db,"C");profiles.registerDomains("W",listOf(ProgressionDomainDefinition("D","W","d","D","generic",definitionVersion=1,provenance="pack")));profiles.saveTalent(TalentEntry("C","P","D",0.9,provenance="t"));profiles.savePotential(PotentialEntry("C","P","D","growth",0.2,provenance="p"));val ss=SkillStore(db,"C");ss.registerDefinitions("W",listOf(skill("S")));ss.savePlayerSkill(PlayerSkill("C","P","S",90.0,provenance="s"));val ts=TechniqueStore(db,"C");ts.registerDefinitions("W",listOf(def("T")));ts.savePlayerTechnique(PlayerTechnique("C","P","T",30.0,provenance="t"));profiles.saveTalent(TalentEntry("C","P","D",0.1,2,"t2"));profiles.savePotential(PotentialEntry("C","P","D","growth",0.8,2,"p2"));ss.savePlayerSkill(PlayerSkill("C","P","S",10.0,provenance="s2"));assertEquals(30.0,ts.playerTechniques("P").single().baseMastery,0.0)}}

    @Test fun invalidMasteryNaNInfinityRangeAndWrongTargetFail(){open().use{db->MigrationManager().ensureV8(db,"C");val s=TechniqueStore(db,"C");s.registerDefinitions("W",listOf(def("T",max=100.0),def("U",key="u",max=null)));expectFailure{s.savePlayerTechnique(PlayerTechnique("C","P","T",-1.0,provenance="x"))};expectFailure{s.savePlayerTechnique(PlayerTechnique("C","P","T",Double.NaN,provenance="x"))};expectFailure{s.savePlayerTechnique(PlayerTechnique("C","P","T",Double.POSITIVE_INFINITY,provenance="x"))};expectFailure{s.savePlayerTechnique(PlayerTechnique("C","P","T",101.0,provenance="x"))};s.savePlayerTechnique(PlayerTechnique("C","P","U",1.0e200,provenance="x"));val p=s.playerTechniques("P").single{it.techniqueUid=="U"};expectFailure{DerivedValueResolver().resolve(DerivedResolutionRequest("C","P",0,emptyList(),emptyList(),emptyList(),emptyList(),listOf(Modifier("wrong","C","P","U",ModifierTargetKind.SKILL_EFFECTIVE,ModifierLifecycle.TEMPORARY,ModifierOperation.ADD_FLAT,1.0,sourceType="T",sourceUid="x",provenance="x")),techniqueDefinitions=s.definitions(),playerTechniques=listOf(p)))}}}

    @Test fun canonIndexNameDoesNotCreateOrLinkDefinition(){open().use{db->MigrationManager().ensureV8(db,"C");db.execSQL("CREATE TABLE canon_technique_index(technique_uid TEXT,name TEXT)");db.execSQL("INSERT INTO canon_technique_index VALUES('CANON-INDEX','Same Name')");val s=TechniqueStore(db,"C");assertTrue(s.definitions().isEmpty());s.registerDefinitions("W",listOf(def("T",name="Same Name")));assertEquals("T",s.definitions().single().techniqueUid)}}

    @Test fun migrationIdempotentCurrentSchemaPreservesPhase7AndModifierRows(){open().use{db->MigrationManager().ensureV7(db,"C");val ss=SkillStore(db,"C");ss.registerDefinitions("W",listOf(skill("S")));ss.savePlayerSkill(PlayerSkill("C","P","S",44.0,provenance="phase7"));ModifierStore(db,"C").save(Modifier("old","C","P","S",ModifierTargetKind.SKILL_EFFECTIVE,ModifierLifecycle.INJURY,ModifierOperation.ADD_FLAT,-1.0,sourceType="T",sourceUid="S",provenance="old"));CurrentSchema.ensure(db,"C");CurrentSchema.ensure(db,"C");assertEquals(1,scalarInt(db,"SELECT COUNT(*) FROM rpgos_schema_migrations WHERE migration_id='$PHASE8_MIGRATION_ID'"));assertEquals(44.0,SkillStore(db,"C").playerSkills("P").single().baseMastery,0.0);assertEquals(1,scalarInt(db,"SELECT COUNT(*) FROM modifiers WHERE modifier_uid='old'"));assertTrue(scalarText(db,"SELECT sql FROM sqlite_master WHERE type='table' AND name='modifiers'").contains("TECHNIQUE_EFFECTIVE"));assertEquals(1,scalarInt(db,"SELECT COUNT(*) FROM sqlite_master WHERE type='table' AND name='player_techniques_v2'"))}}

    @Test fun thousandTechniquesNoTruncationIntegrityAndFkClean(){open().use{db->db.execSQL("PRAGMA foreign_keys=ON");MigrationManager().ensureV8(db,"C");val s=TechniqueStore(db,"C");val defs=(0 until 1005).map{i->def("T%04d".format(i),"k%04d".format(i))};s.registerDefinitions("W",defs);db.beginTransaction();try{defs.forEachIndexed{i,d->s.savePlayerTechnique(PlayerTechnique("C","P",d.techniqueUid,i.toDouble(),usageCount=i.toLong(),successCount=(i/2).toLong(),failureCount=(i/3).toLong(),provenance="bulk"))};db.setTransactionSuccessful()}finally{db.endTransaction()};assertEquals(1005,s.playerTechniques("P").size);db.rawQuery("PRAGMA integrity_check",null).use{c->assertTrue(c.moveToFirst());assertEquals("ok",c.getString(0))};db.rawQuery("PRAGMA foreign_key_check",null).use{c->assertFalse(c.moveToFirst())}}}

    private fun def(uid:String,key:String=uid.lowercase(),pack:String="W",name:String="Technique $uid",req:List<TechniqueSkillRequirement> = emptyList(),cost:List<TechniqueResourceCost> = emptyList(),max:Double?=null)=TechniqueDefinition(uid,pack,key,name,"generic",req,cost,0.0,max,TechniqueDefinitionStatus.ACTIVE,1,"world-pack")
    private fun req(skillUid:String,phase:TechniqueRequirementPhase,basis:TechniqueSkillMasteryBasis,min:Double)=TechniqueSkillRequirement(skillUid,phase,basis,min,1,"pack")
    private fun skill(uid:String)=SkillDefinition(uid,"W",uid.lowercase(),"Skill $uid","generic",provenance="world-pack")
    private fun tmod(uid:String,value:Double,priority:Int=0)=Modifier(uid,"C","P","T",ModifierTargetKind.TECHNIQUE_EFFECTIVE,ModifierLifecycle.TEMPORARY,ModifierOperation.ADD_FLAT,value,priority,sourceType="TEST",sourceUid=uid,provenance="test")
    private fun legacyTables(db:SQLiteDatabase){db.execSQL("CREATE TABLE technique_definitions(technique_uid TEXT PRIMARY KEY,name TEXT,category TEXT,base_chakra_cost REAL)");db.execSQL("CREATE TABLE character_techniques(entity_uid TEXT,technique_uid TEXT,mastery REAL,xp REAL,learned_chapter INTEGER,last_used_chapter INTEGER,usage_count INTEGER,success_count INTEGER,failure_count INTEGER,is_equipped INTEGER,notes TEXT,chakra_cost_override REAL)")}
    private fun legacyDump(db:SQLiteDatabase)=db.rawQuery("SELECT entity_uid||'|'||technique_uid||'|'||CAST(mastery AS TEXT)||'|'||CAST(xp AS TEXT)||'|'||COALESCE(CAST(learned_chapter AS TEXT),'')||'|'||COALESCE(CAST(last_used_chapter AS TEXT),'')||'|'||CAST(usage_count AS TEXT)||'|'||CAST(success_count AS TEXT)||'|'||CAST(failure_count AS TEXT)||'|'||CAST(is_equipped AS TEXT)||'|'||COALESCE(notes,'')||'|'||COALESCE(CAST(chakra_cost_override AS TEXT),'') FROM character_techniques ORDER BY technique_uid",null).use{c->buildList{while(c.moveToNext())add(c.getString(0))}}
    private fun open()=SQLiteDatabase.openOrCreateDatabase(dbFile,null)
    private fun scalarInt(db:SQLiteDatabase,sql:String)=db.rawQuery(sql,null).use{c->require(c.moveToFirst());c.getInt(0)}
    private fun scalarText(db:SQLiteDatabase,sql:String)=db.rawQuery(sql,null).use{c->require(c.moveToFirst());c.getString(0)}
    private fun expectFailure(block:()->Unit){try{block();fail("Expected failure")}catch(_:IllegalArgumentException){}catch(_:IllegalStateException){}}
}
